import type { PresetSpot } from './config';

/**
 * München (Auftrag 38): zwei Spots pro Stadtbezirk, alles zum Freischalten, teurer als in Hamburg (Freischalten etwa
 * doppelt so viel wie in Köln) und mit höheren Preisen. Weniger Spots als anderswo, dafür zahlt die Kundschaft mehr.
 */
export const PRESET_SPOTS_MUENCHEN: readonly PresetSpot[] = [
  {
    id: 'viktualienmarkt',
    name: 'Viktualienmarkt',
    lng: 11.5785,
    lat: 48.1362,
    demand: 1.2,
    priceMultiplier: 1.3,
    unlockCost: 2600,
    audience: { tourist: 1.8, banker: 1.3 },
  },
  {
    id: 'sendlinger-tor',
    name: 'Sendlinger Tor',
    lng: 11.5665,
    lat: 48.134,
    demand: 1.3,
    priceMultiplier: 1.2,
    unlockCost: 2200,
    audience: { party: 1.4, student: 1.2, tourist: 1.2 },
  },
  {
    id: 'theresienwiese',
    name: 'Theresienwiese',
    lng: 11.553,
    lat: 48.134,
    demand: 1.0,
    priceMultiplier: 1.25,
    unlockCost: 2400,
    audience: { tourist: 2.0, party: 1.8 },
  },
  {
    id: 'hauptbahnhof-muc',
    name: 'Hauptbahnhof Süd',
    lng: 11.5605,
    lat: 48.1405,
    demand: 1.5,
    priceMultiplier: 1.05,
    unlockCost: 1800,
    audience: { stoner: 1.6, party: 1.2, tourist: 1.1, banker: 0.4 },
  },
  {
    id: 'uni-muc',
    name: 'Geschwister-Scholl-Platz',
    lng: 11.5803,
    lat: 48.1505,
    demand: 1.2,
    priceMultiplier: 1.15,
    unlockCost: 1900,
    audience: { student: 2.0, stoner: 1.2 },
  },
  {
    id: 'augustiner-keller',
    name: 'Biergarten Augustiner-Keller',
    kind: 'kneipe',
    lng: 11.553,
    lat: 48.1437,
    demand: 0.8,
    priceMultiplier: 1.25,
    unlockCost: 2400,
    audience: { tourist: 1.4, banker: 1.2, party: 1.0, student: 0.8 },
  },
  {
    id: 'hohenzollernplatz',
    name: 'Hohenzollernplatz',
    lng: 11.569,
    lat: 48.1612,
    demand: 1.0,
    priceMultiplier: 1.3,
    unlockCost: 2300,
    audience: { banker: 1.6, party: 0.9 },
  },
  {
    id: 'scheidplatz',
    name: 'Scheidplatz',
    lng: 11.5735,
    lat: 48.1705,
    demand: 1.1,
    priceMultiplier: 1.15,
    unlockCost: 1700,
    audience: { stoner: 1.3, student: 1.2 },
  },
  {
    id: 'weissenburger-platz',
    name: 'Weißenburger Platz',
    lng: 11.5965,
    lat: 48.1292,
    demand: 1.1,
    priceMultiplier: 1.25,
    unlockCost: 2100,
    audience: { party: 1.5, banker: 1.1 },
  },
  {
    id: 'ostbahnhof-muc',
    name: 'Ostbahnhof',
    lng: 11.6035,
    lat: 48.1282,
    demand: 1.3,
    priceMultiplier: 1.1,
    unlockCost: 1800,
    audience: { party: 1.8, stoner: 1.2 },
  },
  {
    id: 'harras',
    name: 'Harras',
    lng: 11.5362,
    lat: 48.1172,
    demand: 1.1,
    priceMultiplier: 1.05,
    unlockCost: 1600,
    audience: { stoner: 1.4, party: 0.9 },
  },
  {
    id: 'grossmarkthalle',
    name: 'Großmarkthalle',
    lng: 11.556,
    lat: 48.115,
    demand: 0.8,
    priceMultiplier: 1.1,
    unlockCost: 1600,
    audience: { stoner: 1.2, party: 1.1, banker: 0.6 },
  },
  {
    id: 'gollierplatz',
    name: 'Gollierplatz',
    lng: 11.5355,
    lat: 48.1357,
    demand: 1.0,
    priceMultiplier: 1.05,
    unlockCost: 1600,
    audience: { student: 1.3, stoner: 1.4 },
  },
  {
    id: 'bavariapark',
    name: 'Bavariapark',
    lng: 11.5455,
    lat: 48.1345,
    demand: 0.9,
    priceMultiplier: 1.1,
    unlockCost: 1700,
    audience: { stoner: 1.5, tourist: 1.1 },
  },
  {
    id: 'rotkreuzplatz',
    name: 'Rotkreuzplatz',
    lng: 11.5345,
    lat: 48.153,
    demand: 1.1,
    priceMultiplier: 1.25,
    unlockCost: 2100,
    audience: { banker: 1.3, student: 1.0 },
  },
  {
    id: 'hirschgarten',
    name: 'Hirschgarten',
    lng: 11.5205,
    lat: 48.1515,
    demand: 0.8,
    priceMultiplier: 1.3,
    unlockCost: 2000,
    audience: { banker: 1.4, party: 1.1, tourist: 0.8 },
  },
  {
    id: 'muenchner-freiheit',
    name: 'Münchner Freiheit',
    lng: 11.5865,
    lat: 48.1617,
    demand: 1.3,
    priceMultiplier: 1.25,
    unlockCost: 2300,
    audience: { party: 1.6, student: 1.3, tourist: 1.0 },
  },
  {
    id: 'froettmaning',
    name: 'Fröttmaning (Arena)',
    lng: 11.6232,
    lat: 48.2112,
    demand: 0.6,
    priceMultiplier: 1.2,
    unlockCost: 1600,
    audience: { party: 1.6, tourist: 1.4 },
  },
  {
    id: 'tegernseer-landstrasse',
    name: 'Tegernseer Landstraße',
    lng: 11.5895,
    lat: 48.1135,
    demand: 1.2,
    priceMultiplier: 1.0,
    unlockCost: 1500,
    audience: { stoner: 1.5, party: 1.2 },
  },
  {
    id: 'giesing-sued',
    name: 'Wettbüro Giesing',
    lng: 11.5935,
    lat: 48.108,
    demand: 1.0,
    priceMultiplier: 1.0,
    unlockCost: 1500,
    audience: { stoner: 1.4, party: 1.0, banker: 0.5 },
  },
  {
    id: 'arabellapark',
    name: 'Arabellapark',
    lng: 11.6175,
    lat: 48.1525,
    demand: 0.8,
    priceMultiplier: 1.35,
    unlockCost: 2600,
    audience: { banker: 1.8, tourist: 0.9 },
  },
  {
    id: 'herkomerplatz',
    name: 'Herkomerplatz',
    lng: 11.6085,
    lat: 48.153,
    demand: 0.6,
    priceMultiplier: 1.4,
    unlockCost: 2800,
    audience: { banker: 2.0, stoner: 0.6, student: 0.5 },
  },
  {
    id: 'olympiadorf',
    name: 'Olympiadorf',
    lng: 11.55,
    lat: 48.1805,
    demand: 1.1,
    priceMultiplier: 1.05,
    unlockCost: 1600,
    audience: { student: 1.8, stoner: 1.3 },
  },
  {
    id: 'harthof',
    name: 'Harthof',
    lng: 11.577,
    lat: 48.205,
    demand: 1.0,
    priceMultiplier: 0.95,
    unlockCost: 1500,
    audience: { stoner: 1.5, party: 0.9, banker: 0.3 },
  },
];

/** München: Nachbarn nah beieinander (Wiesn und Bavariapark, Weißenburger Platz und Ostbahnhof) auf verschiedenen Seiten. */
export const SPOT_LABELS_MUENCHEN: Readonly<Record<string, { labelSide: 'left' | 'right'; labelOffsetY: number }>> = {
  viktualienmarkt: { labelSide: 'right', labelOffsetY: 0 },
  'sendlinger-tor': { labelSide: 'left', labelOffsetY: 0 },
  theresienwiese: { labelSide: 'right', labelOffsetY: 0 },
  'hauptbahnhof-muc': { labelSide: 'right', labelOffsetY: 0 },
  'uni-muc': { labelSide: 'right', labelOffsetY: 0 },
  'augustiner-keller': { labelSide: 'left', labelOffsetY: 0 },
  hohenzollernplatz: { labelSide: 'left', labelOffsetY: 0 },
  scheidplatz: { labelSide: 'right', labelOffsetY: 0 },
  'weissenburger-platz': { labelSide: 'left', labelOffsetY: 0 },
  'ostbahnhof-muc': { labelSide: 'right', labelOffsetY: 0 },
  harras: { labelSide: 'left', labelOffsetY: 0 },
  grossmarkthalle: { labelSide: 'right', labelOffsetY: 0 },
  gollierplatz: { labelSide: 'left', labelOffsetY: 0 },
  bavariapark: { labelSide: 'left', labelOffsetY: 0 },
  rotkreuzplatz: { labelSide: 'right', labelOffsetY: 0 },
  hirschgarten: { labelSide: 'left', labelOffsetY: 0 },
  'muenchner-freiheit': { labelSide: 'right', labelOffsetY: 0 },
  froettmaning: { labelSide: 'right', labelOffsetY: 0 },
  'tegernseer-landstrasse': { labelSide: 'right', labelOffsetY: 0 },
  'giesing-sued': { labelSide: 'left', labelOffsetY: 0 },
  arabellapark: { labelSide: 'right', labelOffsetY: 0 },
  herkomerplatz: { labelSide: 'left', labelOffsetY: 0 },
  olympiadorf: { labelSide: 'left', labelOffsetY: 0 },
  harthof: { labelSide: 'right', labelOffsetY: 0 },
};
