import type { Spot } from './index';

/** Vorgegebener Spot ohne Veedel: Das Veedel ergibt sich aus der Lage (veedelAt, siehe presetSpots in index.ts). */
export type PresetSpot = Omit<Spot, 'veedelId'>;

/**
 * Vorgegebene Spots. Die mit unlockCost 0 sind von Anfang an offen, die anderen muss man freischalten
 * (Schwarzgeld für Kontakte vor Ort). audience: wie stark ein Kundentyp hier vertreten ist (1 = normal). In Sülz,
 * Lindenthal und Neustadt-Süd gibt es seit Auftrag 30 mehr Studenten (zahlen weniger, kommen oft).
 */
export const PRESET_SPOTS: readonly PresetSpot[] = [
  {
    id: 'ebertplatz',
    name: 'Ebertplatz',
    lng: 6.9575,
    lat: 50.9497,
    demand: 1.4,
    priceMultiplier: 0.9,
    unlockCost: 0,
    audience: { stoner: 1.6, party: 1.2, banker: 0.3 },
  },
  {
    id: 'neumarkt',
    name: 'Neumarkt',
    lng: 6.9476,
    lat: 50.9362,
    demand: 1.3,
    priceMultiplier: 1.0,
    unlockCost: 0,
    audience: { tourist: 1.6, banker: 1.2 },
  },
  {
    id: 'aachener-weiher',
    name: 'Aachener Weiher',
    lng: 6.9282,
    lat: 50.9356,
    demand: 1.1,
    priceMultiplier: 1.1,
    unlockCost: 450,
    audience: { student: 1.8, stoner: 1.3 },
  },
  {
    id: 'zuelpicher',
    name: 'Zülpicher Platz',
    lng: 6.9398,
    lat: 50.9317,
    demand: 1.5,
    priceMultiplier: 1.05,
    unlockCost: 0,
    audience: { student: 1.8, party: 1.8 },
  },
  {
    id: 'rudolfplatz',
    name: 'Rudolfplatz',
    lng: 6.9392,
    lat: 50.9366,
    demand: 1.0,
    priceMultiplier: 1.15,
    unlockCost: 600,
    audience: { party: 1.6, banker: 1.3 },
  },
  {
    id: 'friesenplatz',
    name: 'Friesenplatz',
    lng: 6.9395,
    lat: 50.9407,
    demand: 0.9,
    priceMultiplier: 1.2,
    unlockCost: 700,
    audience: { party: 1.8, banker: 1.2 },
  },
  {
    id: 'breslauer',
    name: 'Breslauer Platz',
    lng: 6.9612,
    lat: 50.9442,
    demand: 1.0,
    priceMultiplier: 0.85,
    unlockCost: 350,
    audience: { tourist: 1.8, stoner: 1.3 },
  },
  {
    id: 'rheinpark',
    name: 'Rheinpark',
    lng: 6.979,
    lat: 50.9468,
    demand: 0.7,
    priceMultiplier: 1.1,
    unlockCost: 300,
    audience: { tourist: 1.5, stoner: 1.2 },
  },
  {
    id: 'stadtgarten',
    name: 'Stadtgarten',
    lng: 6.933,
    lat: 50.9422,
    demand: 0.8,
    priceMultiplier: 1.1,
    unlockCost: 400,
    audience: { student: 1.2, stoner: 1.3 },
  },
  {
    id: 'uni',
    name: 'Uni-Wiese',
    lng: 6.929,
    lat: 50.9282,
    demand: 1.0,
    priceMultiplier: 1.0,
    unlockCost: 0,
    audience: { student: 2.8, banker: 0.3 },
  },
  // --- Auftrag 28: Jedes Veedel hat mindestens zwei Spots, mindestens einen zum Kaufen. Die Schäl Sick (Deutz,
  // Kalk, Mülheim) und Bayenthal sind Ziele fürs mittlere Spiel: teurer im Freischalten, dafür lohnend. ---
  {
    id: 'domplatte',
    name: 'Domplatte',
    lng: 6.9576,
    lat: 50.9413,
    demand: 1.3,
    priceMultiplier: 0.95,
    unlockCost: 800,
    audience: { tourist: 2.0, party: 1.0, banker: 0.8 },
  },
  {
    id: 'chlodwigplatz',
    name: 'Chlodwigplatz',
    lng: 6.9596,
    lat: 50.9219,
    demand: 1.1,
    priceMultiplier: 1.0,
    unlockCost: 550,
    audience: { student: 1.2, stoner: 1.3, party: 1.1 },
  },
  {
    id: 'ottoplatz',
    name: 'Deutzer Bahnhof',
    lng: 6.9748,
    lat: 50.941,
    demand: 1.1,
    priceMultiplier: 1.0,
    unlockCost: 900,
    audience: { tourist: 1.4, banker: 1.2, party: 1.0 },
  },
  {
    id: 'venloer',
    name: 'Bahnhof Ehrenfeld',
    lng: 6.9163,
    lat: 50.9516,
    demand: 1.3,
    priceMultiplier: 0.95,
    unlockCost: 650,
    audience: { party: 1.5, student: 1.2, stoner: 1.1 },
  },
  {
    id: 'herbrandstrasse',
    name: 'Herbrandstraße',
    lng: 6.9148,
    lat: 50.9472,
    demand: 1.1,
    priceMultiplier: 1.0,
    unlockCost: 800,
    audience: { party: 1.9, stoner: 1.1, banker: 0.5 },
  },
  {
    id: 'stadtwald',
    name: 'Stadtwald',
    lng: 6.9015,
    lat: 50.9265,
    demand: 0.7,
    priceMultiplier: 1.25,
    unlockCost: 650,
    audience: { banker: 1.3, student: 1.3, stoner: 1.0 },
  },
  {
    id: 'berrenrather',
    name: 'Berrenrather Straße',
    lng: 6.9245,
    lat: 50.9215,
    demand: 1.0,
    priceMultiplier: 1.15,
    unlockCost: 750,
    audience: { banker: 1.2, student: 1.4, stoner: 0.8 },
  },
  {
    id: 'hermeskeiler',
    name: 'Hermeskeiler Platz',
    lng: 6.9086,
    lat: 50.9169,
    demand: 0.8,
    priceMultiplier: 1.2,
    unlockCost: 600,
    audience: { banker: 1.3, stoner: 1.0, party: 0.6, student: 1.2 },
  },
  {
    id: 'wilhelmplatz',
    name: 'Wilhelmplatz',
    lng: 6.9519,
    lat: 50.9607,
    demand: 1.2,
    priceMultiplier: 0.9,
    unlockCost: 700,
    audience: { stoner: 1.5, student: 0.8, banker: 0.6 },
  },
  {
    id: 'florastrasse',
    name: 'Neusser Straße',
    lng: 6.9545,
    lat: 50.9655,
    demand: 0.9,
    priceMultiplier: 0.95,
    unlockCost: 550,
    audience: { stoner: 1.2, tourist: 0.8, party: 0.8 },
  },
  {
    id: 'kalk-post',
    name: 'Kalk Post',
    lng: 7.0005,
    lat: 50.9379,
    demand: 1.3,
    priceMultiplier: 0.8,
    unlockCost: 1200,
    audience: { stoner: 1.6, party: 1.1, banker: 0.2 },
  },
  {
    id: 'ottmar-pohl',
    name: 'Ottmar-Pohl-Platz',
    lng: 7.0078,
    lat: 50.9391,
    demand: 1.0,
    priceMultiplier: 0.8,
    unlockCost: 900,
    audience: { stoner: 1.4, student: 0.9, banker: 0.2 },
  },
  {
    id: 'wiener-platz',
    name: 'Wiener Platz',
    lng: 7.0046,
    lat: 50.9643,
    demand: 1.4,
    priceMultiplier: 0.8,
    unlockCost: 1300,
    audience: { stoner: 1.5, party: 1.1, banker: 0.3 },
  },
  {
    id: 'muelheimer-hafen',
    name: 'Mülheimer Hafen',
    lng: 7.001,
    lat: 50.9605,
    demand: 0.8,
    priceMultiplier: 0.9,
    unlockCost: 950,
    audience: { party: 1.3, stoner: 1.1, tourist: 0.7 },
  },
  {
    id: 'suedpark',
    name: 'Südpark',
    lng: 6.964,
    lat: 50.9115,
    demand: 0.7,
    priceMultiplier: 1.3,
    unlockCost: 1000,
    audience: { banker: 1.6, stoner: 0.7, student: 0.6 },
  },
  {
    id: 'rheinufer-bayenthal',
    name: 'Rheinufer Bayenthal',
    lng: 6.97,
    lat: 50.9125,
    demand: 0.6,
    priceMultiplier: 1.25,
    unlockCost: 800,
    audience: { banker: 1.4, tourist: 0.9, party: 0.7 },
  },
  // Hamburg (Auftrag 30): alles zum Freischalten (dort fängst du ohne Spots an), Preise wie in Köln mal 1,5.
  {
    id: 'spielbudenplatz',
    name: 'Spielbudenplatz',
    lng: 9.9637,
    lat: 53.5497,
    demand: 1.6,
    priceMultiplier: 1.1,
    unlockCost: 1500,
    audience: { party: 2.0, tourist: 1.4 },
  },
  {
    id: 'hans-albers-platz',
    name: 'Hans-Albers-Platz',
    lng: 9.9601,
    lat: 53.5493,
    demand: 1.5,
    priceMultiplier: 1.05,
    unlockCost: 1200,
    audience: { party: 1.8, stoner: 1.2 },
  },
  {
    id: 'landungsbruecken',
    name: 'Landungsbrücken',
    lng: 9.9707,
    lat: 53.5455,
    demand: 1.3,
    priceMultiplier: 1.15,
    unlockCost: 1100,
    audience: { tourist: 2.0, party: 0.8 },
  },
  {
    id: 'schulterblatt',
    name: 'Schulterblatt',
    lng: 9.9627,
    lat: 53.5627,
    demand: 1.5,
    priceMultiplier: 1.0,
    unlockCost: 1050,
    audience: { student: 1.6, party: 1.5, stoner: 1.3 },
  },
  {
    id: 'schanzenpark',
    name: 'Schanzenpark',
    lng: 9.9705,
    lat: 53.565,
    demand: 1.1,
    priceMultiplier: 0.95,
    unlockCost: 750,
    audience: { stoner: 1.6, student: 1.3 },
  },
  {
    id: 'fischmarkt',
    name: 'Fischmarkt',
    lng: 9.9535,
    lat: 53.5445,
    demand: 1.2,
    priceMultiplier: 1.1,
    unlockCost: 900,
    audience: { tourist: 1.8, party: 1.2 },
  },
  {
    id: 'grosse-bergstrasse',
    name: 'Große Bergstraße',
    lng: 9.944,
    lat: 53.552,
    demand: 1.0,
    priceMultiplier: 0.95,
    unlockCost: 750,
    audience: { stoner: 1.2, student: 1.1 },
  },
  {
    id: 'ottenser-hauptstrasse',
    name: 'Ottenser Hauptstraße',
    lng: 9.9265,
    lat: 53.5527,
    demand: 1.2,
    priceMultiplier: 1.15,
    unlockCost: 1200,
    audience: { banker: 1.4, student: 1.3 },
  },
  {
    id: 'alma-wartenberg',
    name: 'Alma-Wartenberg-Platz',
    lng: 9.9306,
    lat: 53.556,
    demand: 1.0,
    priceMultiplier: 1.1,
    unlockCost: 900,
    audience: { student: 1.4, party: 1.2 },
  },
  {
    id: 'hansaplatz',
    name: 'Hansaplatz',
    lng: 10.011,
    lat: 53.5547,
    demand: 1.3,
    priceMultiplier: 0.95,
    unlockCost: 1050,
    audience: { stoner: 1.5, party: 1.3, banker: 0.5 },
  },
  {
    id: 'lange-reihe',
    name: 'Lange Reihe',
    lng: 10.014,
    lat: 53.557,
    demand: 1.2,
    priceMultiplier: 1.15,
    unlockCost: 1300,
    audience: { party: 1.5, banker: 1.2, tourist: 1.2 },
  },
  {
    id: 'ueberseeboulevard',
    name: 'Überseeboulevard',
    lng: 9.9985,
    lat: 53.542,
    demand: 1.0,
    priceMultiplier: 1.3,
    unlockCost: 1650,
    audience: { banker: 1.6, tourist: 1.4, stoner: 0.4 },
  },
  {
    id: 'elbphilharmonie',
    name: 'Elbphilharmonie-Plaza',
    lng: 9.984,
    lat: 53.5413,
    demand: 0.9,
    priceMultiplier: 1.35,
    unlockCost: 1950,
    audience: { tourist: 2.0, banker: 1.4, stoner: 0.4 },
  },
  {
    id: 'osterstrasse',
    name: 'Osterstraße',
    lng: 9.953,
    lat: 53.576,
    demand: 1.1,
    priceMultiplier: 1.05,
    unlockCost: 900,
    audience: { student: 1.3, banker: 1.0 },
  },
  {
    id: 'am-weiher',
    name: 'Am Weiher',
    lng: 9.9505,
    lat: 53.5745,
    demand: 0.9,
    priceMultiplier: 1.05,
    unlockCost: 750,
    audience: { student: 1.4, stoner: 1.2 },
  },
  {
    id: 'eppendorfer-baum',
    name: 'Eppendorfer Baum',
    lng: 9.9846,
    lat: 53.585,
    demand: 1.0,
    priceMultiplier: 1.3,
    unlockCost: 1500,
    audience: { banker: 1.8, student: 0.6 },
  },
  {
    id: 'isemarkt',
    name: 'Isemarkt',
    lng: 9.978,
    lat: 53.587,
    demand: 0.9,
    priceMultiplier: 1.25,
    unlockCost: 1200,
    audience: { banker: 1.6, tourist: 0.8 },
  },
  {
    id: 'fuhlsbuettler-strasse',
    name: 'Fuhlsbüttler Straße',
    lng: 10.042,
    lat: 53.583,
    demand: 1.0,
    priceMultiplier: 0.95,
    unlockCost: 700,
    audience: { stoner: 1.2, party: 1.0 },
  },
  {
    id: 'museumsplatz',
    name: 'Museumsplatz',
    lng: 10.04,
    lat: 53.581,
    demand: 0.8,
    priceMultiplier: 1.0,
    unlockCost: 600,
    audience: { student: 1.2, tourist: 1.0 },
  },
  {
    id: 'stuebenplatz',
    name: 'Stübenplatz',
    lng: 10.0098,
    lat: 53.5008,
    demand: 1.0,
    priceMultiplier: 0.85,
    unlockCost: 600,
    audience: { stoner: 1.8, student: 1.0, banker: 0.3 },
  },
  {
    id: 'reiherstieg',
    name: 'Reiherstieg',
    lng: 9.9925,
    lat: 53.506,
    demand: 0.9,
    priceMultiplier: 0.85,
    unlockCost: 700,
    audience: { stoner: 1.6, party: 1.0, banker: 0.3 },
  },
  {
    id: 'harburger-rathausplatz',
    name: 'Harburger Rathausplatz',
    lng: 9.984,
    lat: 53.4605,
    demand: 1.0,
    priceMultiplier: 0.9,
    unlockCost: 700,
    audience: { student: 1.3, stoner: 1.2 },
  },
  {
    id: 'harburger-sand',
    name: 'Sand',
    lng: 9.9878,
    lat: 53.4614,
    demand: 0.9,
    priceMultiplier: 0.9,
    unlockCost: 600,
    audience: { stoner: 1.3, tourist: 0.8 },
  },
  {
    id: 'blankeneser-markt',
    name: 'Blankeneser Markt',
    lng: 9.8085,
    lat: 53.5626,
    demand: 0.8,
    priceMultiplier: 1.4,
    unlockCost: 1300,
    audience: { banker: 2.0, tourist: 1.0, stoner: 0.3 },
  },
  {
    id: 'strandweg',
    name: 'Strandweg',
    lng: 9.8,
    lat: 53.558,
    demand: 0.7,
    priceMultiplier: 1.35,
    unlockCost: 1100,
    audience: { banker: 1.6, tourist: 1.6, stoner: 0.3 },
  },
  // Veedel-Kneipen (Auftrag 30, Etappe 7): zum Kaufen, offen 17 bis 1 Uhr, weniger Laufkundschaft, viele Stammgäste.
  {
    id: 'kneipe-severin',
    name: 'Kneipe Severinstraße',
    kind: 'kneipe',
    lng: 6.9588,
    lat: 50.9262,
    demand: 0.75,
    priceMultiplier: 1.1,
    unlockCost: 1100,
    audience: { stoner: 1.3, party: 1.2, student: 1.0, tourist: 0.4 },
  },
  {
    id: 'kneipe-koerner',
    name: 'Kneipe Körnerstraße',
    kind: 'kneipe',
    lng: 6.9196,
    lat: 50.9478,
    demand: 0.75,
    priceMultiplier: 1.05,
    unlockCost: 1000,
    audience: { student: 1.4, stoner: 1.3, party: 1.1, banker: 0.5 },
  },
  {
    id: 'kneipe-nippes',
    name: 'Kneipe Neusser Straße',
    kind: 'kneipe',
    lng: 6.9565,
    lat: 50.9625,
    demand: 0.7,
    priceMultiplier: 1.0,
    unlockCost: 900,
    audience: { stoner: 1.4, party: 1.0, banker: 0.6, tourist: 0.3 },
  },
  {
    id: 'kneipe-suelz',
    name: 'Kneipe Sülzburgstraße',
    kind: 'kneipe',
    lng: 6.9215,
    lat: 50.918,
    demand: 0.7,
    priceMultiplier: 1.1,
    unlockCost: 1000,
    audience: { student: 1.6, banker: 1.0, stoner: 0.9, tourist: 0.3 },
  },
  {
    id: 'kiezbar',
    name: 'Kiez-Bar Hamburger Berg',
    kind: 'kneipe',
    lng: 9.9572,
    lat: 53.5508,
    demand: 0.85,
    priceMultiplier: 1.15,
    unlockCost: 1800,
    audience: { party: 1.6, stoner: 1.3, tourist: 1.0 },
  },
];

/**
 * Die zehn Spots aus der Zeit vor Auftrag 28. Spielstände der Version 1 (alle Spots offen) bekommen nur diese
 * offen; die neuen Spots bleiben für alte Spielstände gesperrt.
 */
export const ORIGINAL_SPOT_IDS: readonly string[] = [
  'ebertplatz',
  'neumarkt',
  'aachener-weiher',
  'zuelpicher',
  'rudolfplatz',
  'friesenplatz',
  'breslauer',
  'rheinpark',
  'stadtgarten',
  'uni',
];

/**
 * Veedel-Kneipen (Auftrag 30, Etappe 7): offen von 17 bis 1 Uhr, weniger Laufkundschaft (niedriger demand im Preset),
 * Stammkunden regularFactor-mal so oft, Ruf-Änderungen dort reputationFactor-fach, Preisempfindlichkeit der Gäste mal
 * priceSensitivity (sie schauen weniger auf den Preis).
 */
export const KNEIPE = { from: 17, to: 1, regularFactor: 2, reputationFactor: 2, priceSensitivity: 0.7 } as const;

/** Eigenen Spot gründen kostet so viel Schwarzgeld. */
export const FOUND_SPOT_COST = 800;
/** Höchstens so viele eigene Spots. */
export const MAX_CUSTOM_SPOTS = 6;
/** Mindestabstand eines neuen Spots zu allen anderen in Metern. */
export const MIN_SPOT_DISTANCE = 200;
/** Andrang eines eigenen Spots (wird mit der Dichte des Veedels multipliziert). */
export const CUSTOM_SPOT_DEMAND = 0.8;

/**
 * Plakette neben dem Spot-Schild auf der Karte (Look "Glas"): Seite und senkrechter Versatz in px (positiv = nach
 * unten), damit sich in der Innenstadt (Rudolfplatz, Neumarkt, Zülpicher, Friesenplatz) nichts überdeckt. Geprüft
 * beim Standard-Zoom (13,6) mit allen Spots offen. Eigene Spots und fehlende Einträge: rechts, ohne Versatz.
 */
export const SPOT_LABELS: Readonly<Record<string, { labelSide: 'left' | 'right'; labelOffsetY: number }>> = {
  ebertplatz: { labelSide: 'right', labelOffsetY: 0 },
  neumarkt: { labelSide: 'right', labelOffsetY: 0 },
  'aachener-weiher': { labelSide: 'left', labelOffsetY: 0 },
  zuelpicher: { labelSide: 'left', labelOffsetY: 0 },
  rudolfplatz: { labelSide: 'right', labelOffsetY: 0 },
  friesenplatz: { labelSide: 'right', labelOffsetY: 0 },
  breslauer: { labelSide: 'right', labelOffsetY: 0 },
  rheinpark: { labelSide: 'right', labelOffsetY: 0 },
  stadtgarten: { labelSide: 'left', labelOffsetY: 0 },
  uni: { labelSide: 'left', labelOffsetY: 0 },
  domplatte: { labelSide: 'left', labelOffsetY: 0 },
  chlodwigplatz: { labelSide: 'right', labelOffsetY: 0 },
  ottoplatz: { labelSide: 'right', labelOffsetY: 0 },
  venloer: { labelSide: 'right', labelOffsetY: 0 },
  herbrandstrasse: { labelSide: 'left', labelOffsetY: 0 },
  stadtwald: { labelSide: 'left', labelOffsetY: 0 },
  berrenrather: { labelSide: 'right', labelOffsetY: 0 },
  hermeskeiler: { labelSide: 'left', labelOffsetY: 0 },
  wilhelmplatz: { labelSide: 'left', labelOffsetY: 0 },
  florastrasse: { labelSide: 'right', labelOffsetY: 0 },
  'kalk-post': { labelSide: 'left', labelOffsetY: 0 },
  'ottmar-pohl': { labelSide: 'right', labelOffsetY: 0 },
  'wiener-platz': { labelSide: 'right', labelOffsetY: 0 },
  'muelheimer-hafen': { labelSide: 'left', labelOffsetY: 0 },
  suedpark: { labelSide: 'left', labelOffsetY: 0 },
  'rheinufer-bayenthal': { labelSide: 'right', labelOffsetY: 0 },
  'kneipe-severin': { labelSide: 'right', labelOffsetY: 0 },
  'kneipe-koerner': { labelSide: 'left', labelOffsetY: 0 },
  'kneipe-nippes': { labelSide: 'right', labelOffsetY: 0 },
  'kneipe-suelz': { labelSide: 'left', labelOffsetY: 0 },
  // Hamburg: Nachbarn nah beieinander bekommen Plaketten auf verschiedenen Seiten.
  spielbudenplatz: { labelSide: 'right', labelOffsetY: 0 },
  kiezbar: { labelSide: 'left', labelOffsetY: -22 },
  'hans-albers-platz': { labelSide: 'left', labelOffsetY: 0 },
  landungsbruecken: { labelSide: 'right', labelOffsetY: 0 },
  schulterblatt: { labelSide: 'left', labelOffsetY: 0 },
  schanzenpark: { labelSide: 'right', labelOffsetY: 0 },
  fischmarkt: { labelSide: 'left', labelOffsetY: 0 },
  'grosse-bergstrasse': { labelSide: 'left', labelOffsetY: 0 },
  'ottenser-hauptstrasse': { labelSide: 'left', labelOffsetY: 0 },
  'alma-wartenberg': { labelSide: 'right', labelOffsetY: 0 },
  hansaplatz: { labelSide: 'left', labelOffsetY: 0 },
  'lange-reihe': { labelSide: 'right', labelOffsetY: 0 },
  ueberseeboulevard: { labelSide: 'right', labelOffsetY: 0 },
  elbphilharmonie: { labelSide: 'left', labelOffsetY: 0 },
  osterstrasse: { labelSide: 'right', labelOffsetY: 0 },
  'am-weiher': { labelSide: 'left', labelOffsetY: 0 },
  'eppendorfer-baum': { labelSide: 'right', labelOffsetY: 0 },
  isemarkt: { labelSide: 'left', labelOffsetY: 0 },
  'fuhlsbuettler-strasse': { labelSide: 'right', labelOffsetY: 0 },
  museumsplatz: { labelSide: 'left', labelOffsetY: 0 },
  stuebenplatz: { labelSide: 'right', labelOffsetY: 0 },
  reiherstieg: { labelSide: 'left', labelOffsetY: 0 },
  'harburger-rathausplatz': { labelSide: 'left', labelOffsetY: 0 },
  'harburger-sand': { labelSide: 'right', labelOffsetY: 0 },
  'blankeneser-markt': { labelSide: 'right', labelOffsetY: 0 },
  strandweg: { labelSide: 'left', labelOffsetY: 0 },
};
