import type { PresetSpot } from './config';

/** Freitag 22 Uhr bis Montag 8 Uhr als Stunden der Woche (0 = Montag 0 Uhr): das Berliner Club-Wochenende. */
export const CLUB_WEEKEND: readonly [number, number] = [4 * 24 + 22, 8];

/**
 * Berlin (Auftrag 37): viele Spots, alle zum Freischalten (dort fängst du ohne Spots an), Preise wie in Köln mal dem
 * Immobilien-Faktor 1,2. Der Dreh ist die Nacht: Vier Clubs haben nur am Wochenende offen (CLUB_WEEKEND), dann aber mit
 * dem größten Andrang der Stadt; RAW-Gelände, Kulturbrauerei und Nollendorfplatz sind Club-Ecken, die immer laufen.
 */
export const PRESET_SPOTS_BERLIN: readonly PresetSpot[] = [
  // Mitte
  {
    id: 'alexanderplatz',
    name: 'Alexanderplatz',
    kind: 'station',
    lng: 13.4113,
    lat: 52.5218,
    demand: 1.5,
    priceMultiplier: 1.0,
    unlockCost: 1100,
    audience: { tourist: 1.8, party: 1.0, banker: 0.8 },
  },
  {
    id: 'hackescher-markt',
    name: 'Hackescher Markt',
    at: 'am Hackeschen Markt',
    lng: 13.4027,
    lat: 52.5234,
    demand: 1.3,
    priceMultiplier: 1.15,
    unlockCost: 1000,
    audience: { tourist: 1.5, banker: 1.3, party: 1.2 },
  },
  {
    id: 'rosenthaler-platz',
    name: 'Rosenthaler Platz',
    lng: 13.4015,
    lat: 52.5296,
    demand: 1.2,
    priceMultiplier: 1.05,
    unlockCost: 900,
    audience: { party: 1.5, student: 1.2 },
  },
  {
    id: 'club-koepenicker',
    name: 'Club Köpenicker Straße',
    kind: 'club',
    weekHours: CLUB_WEEKEND,
    lng: 13.4245,
    lat: 52.51,
    demand: 2.2,
    priceMultiplier: 1.2,
    unlockCost: 1700,
    audience: { party: 2.4, tourist: 1.3, banker: 0.8 },
  },
  // Kreuzberg
  {
    id: 'kottbusser-tor',
    name: 'Kottbusser Tor',
    kind: 'station',
    lng: 13.418,
    lat: 52.4993,
    demand: 1.6,
    priceMultiplier: 0.9,
    unlockCost: 1000,
    audience: { stoner: 1.8, party: 1.3, banker: 0.4 },
  },
  {
    id: 'goerlitzer-park',
    name: 'Görlitzer Park',
    kind: 'park',
    lng: 13.4366,
    lat: 52.4959,
    demand: 1.5,
    priceMultiplier: 0.9,
    unlockCost: 900,
    audience: { stoner: 2.0, tourist: 1.2, student: 1.2 },
  },
  {
    id: 'bergmannstrasse',
    name: 'Bergmannstraße',
    lng: 13.3935,
    lat: 52.489,
    demand: 1.0,
    priceMultiplier: 1.1,
    unlockCost: 750,
    audience: { student: 1.3, banker: 1.1 },
  },
  {
    id: 'club-spreeufer',
    name: 'Club am Spreeufer',
    kind: 'club',
    weekHours: CLUB_WEEKEND,
    lng: 13.4465,
    lat: 52.4995,
    demand: 2.2,
    priceMultiplier: 1.2,
    unlockCost: 1700,
    audience: { party: 2.4, tourist: 1.4 },
  },
  // Friedrichshain
  {
    id: 'warschauer-strasse',
    name: 'Warschauer Straße',
    kind: 'station',
    lng: 13.4495,
    lat: 52.5058,
    demand: 1.6,
    priceMultiplier: 1.0,
    unlockCost: 1100,
    audience: { party: 1.8, tourist: 1.4 },
  },
  {
    id: 'raw-gelaende',
    name: 'RAW-Gelände',
    at: 'auf dem RAW-Gelände',
    kind: 'club',
    lng: 13.4545,
    lat: 52.5075,
    demand: 1.6,
    priceMultiplier: 1.1,
    unlockCost: 1200,
    audience: { party: 2.0, student: 1.2, tourist: 1.2 },
  },
  {
    id: 'boxhagener-platz',
    name: 'Boxhagener Platz',
    lng: 13.4595,
    lat: 52.5105,
    demand: 1.2,
    priceMultiplier: 1.0,
    unlockCost: 800,
    audience: { student: 1.4, stoner: 1.3 },
  },
  {
    id: 'club-halle-ost',
    name: 'Halle am Ostbahnhof',
    kind: 'club',
    weekHours: CLUB_WEEKEND,
    lng: 13.4425,
    lat: 52.5108,
    demand: 2.5,
    priceMultiplier: 1.25,
    unlockCost: 1900,
    audience: { party: 2.6, tourist: 1.4, banker: 0.8 },
  },
  // Neukölln
  {
    id: 'hermannplatz',
    name: 'Hermannplatz',
    kind: 'station',
    lng: 13.4245,
    lat: 52.4868,
    demand: 1.4,
    priceMultiplier: 0.9,
    unlockCost: 850,
    audience: { stoner: 1.5, party: 1.0 },
  },
  {
    id: 'weserstrasse',
    name: 'Weserstraße',
    lng: 13.438,
    lat: 52.4855,
    demand: 1.3,
    priceMultiplier: 1.0,
    unlockCost: 850,
    audience: { party: 1.6, student: 1.5 },
  },
  {
    id: 'richardplatz',
    name: 'Richardplatz',
    lng: 13.444,
    lat: 52.4735,
    demand: 0.9,
    priceMultiplier: 0.95,
    unlockCost: 650,
    audience: { stoner: 1.3 },
  },
  // Prenzlauer Berg
  {
    id: 'mauerpark',
    name: 'Mauerpark',
    kind: 'park',
    lng: 13.405,
    lat: 52.541,
    demand: 1.3,
    priceMultiplier: 1.0,
    unlockCost: 900,
    audience: { stoner: 1.6, tourist: 1.3, student: 1.3 },
  },
  {
    id: 'kollwitzplatz',
    name: 'Kollwitzplatz',
    lng: 13.4175,
    lat: 52.5362,
    demand: 1.0,
    priceMultiplier: 1.2,
    unlockCost: 950,
    audience: { banker: 1.4, party: 0.8 },
  },
  {
    id: 'kulturbrauerei',
    name: 'Kulturbrauerei',
    kind: 'club',
    lng: 13.413,
    lat: 52.539,
    demand: 1.3,
    priceMultiplier: 1.15,
    unlockCost: 1000,
    audience: { party: 1.7, student: 1.2 },
  },
  // Wedding
  {
    id: 'leopoldplatz',
    name: 'Leopoldplatz',
    kind: 'station',
    lng: 13.359,
    lat: 52.5465,
    demand: 1.3,
    priceMultiplier: 0.85,
    unlockCost: 700,
    audience: { stoner: 1.6, banker: 0.4 },
  },
  {
    id: 'muellerstrasse',
    name: 'Müllerstraße',
    lng: 13.349,
    lat: 52.5524,
    demand: 1.0,
    priceMultiplier: 0.9,
    unlockCost: 600,
    audience: { stoner: 1.3, student: 1.1 },
  },
  {
    id: 'rehberge',
    name: 'Volkspark Rehberge',
    kind: 'park',
    lng: 13.34,
    lat: 52.5575,
    demand: 0.9,
    priceMultiplier: 0.9,
    unlockCost: 550,
    audience: { stoner: 1.5, student: 1.2 },
  },
  // Moabit
  {
    id: 'turmstrasse',
    name: 'Turmstraße',
    kind: 'station',
    lng: 13.341,
    lat: 52.5258,
    demand: 1.1,
    priceMultiplier: 0.95,
    unlockCost: 700,
    audience: { stoner: 1.3 },
  },
  {
    id: 'hauptbahnhof',
    name: 'Hauptbahnhof',
    kind: 'station',
    lng: 13.3685,
    lat: 52.5245,
    demand: 1.4,
    priceMultiplier: 1.0,
    unlockCost: 1000,
    audience: { tourist: 1.8, banker: 1.2 },
  },
  {
    id: 'stephanplatz',
    name: 'Stephanplatz',
    lng: 13.347,
    lat: 52.5335,
    demand: 0.8,
    priceMultiplier: 1.0,
    unlockCost: 550,
    audience: { student: 1.2 },
  },
  // Schöneberg
  {
    id: 'nollendorfplatz',
    name: 'Nollendorfplatz',
    kind: 'club',
    lng: 13.3537,
    lat: 52.4995,
    demand: 1.5,
    priceMultiplier: 1.1,
    unlockCost: 1100,
    audience: { party: 1.9, tourist: 1.1 },
  },
  {
    id: 'winterfeldtplatz',
    name: 'Winterfeldtplatz',
    lng: 13.351,
    lat: 52.496,
    demand: 1.0,
    priceMultiplier: 1.15,
    unlockCost: 850,
    audience: { banker: 1.2, student: 1.1 },
  },
  {
    id: 'akazienstrasse',
    name: 'Akazienstraße',
    lng: 13.353,
    lat: 52.487,
    demand: 0.9,
    priceMultiplier: 1.1,
    unlockCost: 700,
    audience: { banker: 1.1, stoner: 1.1 },
  },
  // Charlottenburg
  {
    id: 'savignyplatz',
    name: 'Savignyplatz',
    lng: 13.3222,
    lat: 52.5057,
    demand: 1.0,
    priceMultiplier: 1.3,
    unlockCost: 1100,
    audience: { banker: 1.7, tourist: 1.2 },
  },
  {
    id: 'stuttgarter-platz',
    name: 'Stuttgarter Platz',
    lng: 13.3015,
    lat: 52.5047,
    demand: 1.0,
    priceMultiplier: 1.05,
    unlockCost: 800,
    audience: { party: 1.2, banker: 1.0 },
  },
  {
    id: 'klausenerplatz',
    name: 'Klausenerplatz',
    lng: 13.289,
    lat: 52.5185,
    demand: 0.7,
    priceMultiplier: 1.2,
    unlockCost: 700,
    audience: { banker: 1.4 },
  },
  {
    id: 'ernst-reuter-platz',
    name: 'Ernst-Reuter-Platz',
    kind: 'campus',
    lng: 13.3215,
    lat: 52.5125,
    demand: 1.1,
    priceMultiplier: 0.95,
    unlockCost: 800,
    audience: { student: 2.0, banker: 0.6 },
  },
  // Alt-Treptow
  {
    id: 'treptower-park',
    name: 'Treptower Park',
    kind: 'park',
    lng: 13.469,
    lat: 52.49,
    demand: 1.2,
    priceMultiplier: 0.95,
    unlockCost: 750,
    audience: { stoner: 1.5, tourist: 1.2 },
  },
  {
    id: 'club-eichenstrasse',
    name: 'Club an der Eichenstraße',
    kind: 'club',
    weekHours: CLUB_WEEKEND,
    lng: 13.4595,
    lat: 52.4935,
    demand: 2.0,
    priceMultiplier: 1.15,
    unlockCost: 1500,
    audience: { party: 2.4, student: 1.1 },
  },
  {
    id: 'bouchestrasse',
    name: 'Bouchéstraße',
    lng: 13.452,
    lat: 52.4905,
    demand: 0.9,
    priceMultiplier: 1.0,
    unlockCost: 600,
    audience: { party: 1.3, student: 1.2 },
  },
  // Lichtenberg
  {
    id: 'magdalenenstrasse',
    name: 'U Magdalenenstraße',
    kind: 'station',
    lng: 13.49,
    lat: 52.514,
    demand: 1.1,
    priceMultiplier: 0.85,
    unlockCost: 600,
    audience: { stoner: 1.3, banker: 0.4 },
  },
  {
    id: 'roedeliusplatz',
    name: 'Roedeliusplatz',
    lng: 13.4895,
    lat: 52.5185,
    demand: 0.8,
    priceMultiplier: 0.9,
    unlockCost: 550,
    audience: { stoner: 1.2 },
  },
  {
    id: 'herzbergstrasse',
    name: 'Herzbergstraße',
    lng: 13.4985,
    lat: 52.5262,
    demand: 0.8,
    priceMultiplier: 0.85,
    unlockCost: 500,
    audience: { stoner: 1.4, student: 1.0 },
  },
  // Tempelhof
  {
    id: 'tempelhofer-feld',
    name: 'Tempelhofer Feld',
    at: 'auf dem Tempelhofer Feld',
    kind: 'park',
    lng: 13.3862,
    lat: 52.4795,
    demand: 1.3,
    priceMultiplier: 0.95,
    unlockCost: 800,
    audience: { stoner: 1.6, student: 1.3, tourist: 1.2 },
  },
  {
    id: 'tempelhofer-damm',
    name: 'Tempelhofer Damm',
    kind: 'station',
    lng: 13.3855,
    lat: 52.472,
    demand: 1.0,
    priceMultiplier: 0.95,
    unlockCost: 650,
    audience: { banker: 1.0, stoner: 1.1 },
  },
  {
    id: 'alt-tempelhof',
    name: 'Alt-Tempelhof',
    at: 'in Alt-Tempelhof',
    lng: 13.3855,
    lat: 52.4655,
    demand: 0.8,
    priceMultiplier: 1.0,
    unlockCost: 550,
    audience: { banker: 1.1 },
  },
];

/**
 * Plaketten der Berliner Spots (siehe SPOT_LABELS): Nachbarn nah beieinander bekommen verschiedene Seiten
 * (Alexanderplatz und Hackescher Markt, Warschauer Straße und RAW-Gelände, Kollwitzplatz und Kulturbrauerei …).
 */
export const SPOT_LABELS_BERLIN: Readonly<Record<string, { labelSide: 'left' | 'right'; labelOffsetY: number }>> = {
  alexanderplatz: { labelSide: 'right', labelOffsetY: 0 },
  'hackescher-markt': { labelSide: 'left', labelOffsetY: 0 },
  'rosenthaler-platz': { labelSide: 'left', labelOffsetY: 0 },
  'club-koepenicker': { labelSide: 'right', labelOffsetY: 0 },
  'kottbusser-tor': { labelSide: 'left', labelOffsetY: 0 },
  'goerlitzer-park': { labelSide: 'right', labelOffsetY: 0 },
  bergmannstrasse: { labelSide: 'left', labelOffsetY: 0 },
  'club-spreeufer': { labelSide: 'left', labelOffsetY: 0 },
  'warschauer-strasse': { labelSide: 'left', labelOffsetY: 0 },
  'raw-gelaende': { labelSide: 'right', labelOffsetY: 0 },
  'boxhagener-platz': { labelSide: 'right', labelOffsetY: 0 },
  'club-halle-ost': { labelSide: 'left', labelOffsetY: 0 },
  hermannplatz: { labelSide: 'left', labelOffsetY: 0 },
  weserstrasse: { labelSide: 'right', labelOffsetY: 0 },
  richardplatz: { labelSide: 'right', labelOffsetY: 0 },
  mauerpark: { labelSide: 'left', labelOffsetY: 0 },
  kollwitzplatz: { labelSide: 'right', labelOffsetY: 0 },
  kulturbrauerei: { labelSide: 'left', labelOffsetY: 0 },
  leopoldplatz: { labelSide: 'right', labelOffsetY: 0 },
  muellerstrasse: { labelSide: 'left', labelOffsetY: 0 },
  rehberge: { labelSide: 'left', labelOffsetY: 0 },
  turmstrasse: { labelSide: 'left', labelOffsetY: 0 },
  hauptbahnhof: { labelSide: 'right', labelOffsetY: 0 },
  stephanplatz: { labelSide: 'right', labelOffsetY: 0 },
  nollendorfplatz: { labelSide: 'right', labelOffsetY: 0 },
  winterfeldtplatz: { labelSide: 'left', labelOffsetY: 0 },
  akazienstrasse: { labelSide: 'right', labelOffsetY: 0 },
  savignyplatz: { labelSide: 'right', labelOffsetY: 0 },
  'stuttgarter-platz': { labelSide: 'left', labelOffsetY: 0 },
  klausenerplatz: { labelSide: 'left', labelOffsetY: 0 },
  'ernst-reuter-platz': { labelSide: 'right', labelOffsetY: 0 },
  'treptower-park': { labelSide: 'right', labelOffsetY: 0 },
  'club-eichenstrasse': { labelSide: 'left', labelOffsetY: 0 },
  bouchestrasse: { labelSide: 'left', labelOffsetY: 0 },
  magdalenenstrasse: { labelSide: 'right', labelOffsetY: 0 },
  roedeliusplatz: { labelSide: 'left', labelOffsetY: 0 },
  herzbergstrasse: { labelSide: 'right', labelOffsetY: 0 },
  'tempelhofer-feld': { labelSide: 'right', labelOffsetY: 0 },
  'tempelhofer-damm': { labelSide: 'left', labelOffsetY: 0 },
  'alt-tempelhof': { labelSide: 'right', labelOffsetY: 0 },
};
