import type { Spot } from './index';

/** Vorgegebene Spots aus dem Prototyp, jetzt mit Veedel. Einfach Namen/Koordinaten austauschen oder ergänzen. */
export const PRESET_SPOTS: readonly Spot[] = [
  {
    id: 'ebertplatz',
    name: 'Ebertplatz',
    lng: 6.9575,
    lat: 50.9497,
    veedelId: 'neustadt-nord',
    demand: 1.4,
    priceMultiplier: 0.9,
  },
  {
    id: 'neumarkt',
    name: 'Neumarkt',
    lng: 6.9476,
    lat: 50.9362,
    veedelId: 'altstadt-sued',
    demand: 1.3,
    priceMultiplier: 1.0,
  },
  {
    id: 'aachener-weiher',
    name: 'Aachener Weiher',
    lng: 6.9282,
    lat: 50.9356,
    veedelId: 'neustadt-sued',
    demand: 1.1,
    priceMultiplier: 1.1,
  },
  {
    id: 'zuelpicher',
    name: 'Zülpicher Platz',
    lng: 6.9398,
    lat: 50.9317,
    veedelId: 'neustadt-sued',
    demand: 1.5,
    priceMultiplier: 1.05,
  },
  {
    id: 'rudolfplatz',
    name: 'Rudolfplatz',
    lng: 6.9392,
    lat: 50.9366,
    veedelId: 'neustadt-sued',
    demand: 1.0,
    priceMultiplier: 1.15,
  },
  {
    id: 'friesenplatz',
    name: 'Friesenplatz',
    lng: 6.9395,
    lat: 50.9407,
    veedelId: 'neustadt-nord',
    demand: 0.9,
    priceMultiplier: 1.2,
  },
  {
    id: 'breslauer',
    name: 'Breslauer Platz',
    lng: 6.9612,
    lat: 50.9442,
    veedelId: 'altstadt-nord',
    demand: 1.0,
    priceMultiplier: 0.85,
  },
  {
    id: 'rheinpark',
    name: 'Rheinpark',
    lng: 6.979,
    lat: 50.9468,
    veedelId: 'deutz',
    demand: 0.7,
    priceMultiplier: 1.1,
  },
  {
    id: 'stadtgarten',
    name: 'Stadtgarten',
    lng: 6.933,
    lat: 50.9422,
    veedelId: 'neustadt-nord',
    demand: 0.8,
    priceMultiplier: 1.1,
  },
  { id: 'uni', name: 'Uni-Wiese', lng: 6.929, lat: 50.9282, veedelId: 'lindenthal', demand: 1.0, priceMultiplier: 1.0 },
];
