// Absichten der Gegenseite als reine Daten (Auftrag 35). Jede Runde würfelt die Engine eine Absicht aus der Liste des
// Anlasses (kinds.ts), gewichtet nach den Zeigern: Wer wütend ist, greift eher zu, wer zweifelt, sucht den Ausgang.
// Die Absicht steht als Chip im Dialog, bevor man handelt; was sie tut, passiert am Ende der Runde. Die passende
// Handlung wendet sie ganz ab (counters), ein geschützter Einsatz nimmt nur einen Teil des Schadens (PROTECT_FACTOR).
// modifiers verstärken (>1) oder schwächen (<1) Handlungen.
// Gewichte: base plus aggression (Aggression/100), calm (1 − Aggression/100), resolve (Entschlossenheit/100),
// doubt (1 − Entschlossenheit/100), brawl (1, während geprügelt wird).

import type { EncounterIntent } from './types';

export const ENCOUNTER_INTENTS: Record<string, EncounterIntent> = {
  // --- Gangs, Geschäftspartner ---------------------------------------------------------------
  grabGoods: {
    label: 'Sie gehen auf die Ware',
    icon: 'bag',
    stake: 'goods',
    damage: 40,
    counters: ['fight', 'intimidate'],
    onHit: { resolve: 6 },
    hit: 0.2,
    weight: { base: 1.6, aggression: 1 },
    hitText: 'Einer reißt eine Tasche mit Ware an sich.',
    blockedText: 'Die Ware ist sicher verstaut.',
  },
  grabCash: {
    label: 'Sie gehen auf die Kasse',
    icon: 'moneyBag',
    stake: 'cash',
    damage: 45,
    counters: ['intimidate', 'fight'],
    onHit: { resolve: 6 },
    hit: 0.2,
    weight: { base: 1.3, aggression: 1 },
    hitText: 'Einer greift in die Kasse.',
    blockedText: 'Die Kasse bleibt zu.',
  },
  wreck: {
    label: 'Sie zerlegen den Spot',
    icon: 'flame',
    stake: 'spot',
    damage: 35,
    drift: { aggression: 3 },
    counters: ['fight', 'negotiate'],
    onHit: { resolve: 4 },
    hit: 0.2,
    weight: { base: 0.7, aggression: 0.8, brawl: 0.5 },
    hitText: 'Tische fliegen, Scheiben klirren. Im Veedel spricht sich das rum.',
    blockedText: 'Ihr stellt euch vor den Eingang. Der Spot bleibt heil.',
  },
  knife: {
    label: 'Einer zieht ein Messer',
    icon: 'swords',
    stake: 'people',
    hit: 0.45,
    drift: { aggression: 6 },
    counters: ['hold', 'intimidate'],
    weight: { base: 0.3, aggression: 1.3, brawl: 1 },
    hitText: 'Die Klinge blitzt.',
    blockedText: 'Ihr haltet Abstand. Das Messer findet niemanden.',
  },
  leaderTalks: {
    label: 'Der Anführer will reden',
    icon: 'handshake',
    needs: 'leader',
    drift: { aggression: -4 },
    modifiers: { negotiate: 1.6, bribe: 1.3, bluff: 1.2, intimidate: 0.8, fight: 0.6 },
    weight: { base: 0.5, calm: 1.4 },
    hitText: '',
    blockedText: '',
  },
  exit: {
    label: 'Sie suchen den Ausgang',
    icon: 'logout',
    drift: { resolve: -6 },
    modifiers: { fight: 0.6, negotiate: 1.3, hold: 1.4, bluff: 1.3 },
    weight: { base: 0.1, doubt: 1.6 },
    hitText: '',
    blockedText: '',
  },
  noise: {
    label: 'Es wird laut',
    icon: 'megaphone',
    stake: 'noise',
    heat: 5,
    clock: -1,
    counters: ['hold', 'negotiate'],
    weight: { base: 0.4, aggression: 0.6, brawl: 1.2 },
    hitText: 'Fenster gehen auf. Jemand ruft die Polizei.',
    blockedText: 'Ihr haltet es leise.',
  },
  bruiserUp: {
    label: 'Der Schläger baut sich auf',
    icon: 'fist',
    needs: 'bruiser',
    drift: { aggression: 10 },
    modifiers: { intimidate: 0.7, negotiate: 0.8 },
    counters: ['negotiate', 'hold'],
    weight: { base: 0.5, aggression: 0.6 },
    hitText: 'Der Schläger knackt mit den Fingern. Die anderen werden mutiger.',
    blockedText: 'Der Schläger beruhigt sich wieder.',
  },
  nervousWavers: {
    label: 'Der Nervöse schaut zur Tür',
    icon: 'eye',
    needs: 'nervous',
    drift: { resolve: -4 },
    modifiers: { talkNervous: 1.6, bluff: 1.3 },
    weight: { base: 0.4, doubt: 1 },
    hitText: '',
    blockedText: '',
  },
  // Beim Überfall auf einen Gang-Spot: Die Wachen retten, was sie können.
  hideLoot: {
    label: 'Sie schaffen die Ware weg',
    icon: 'package',
    stake: 'goods',
    damage: 30,
    counters: ['fight', 'intimidate'],
    onHit: { resolve: 4 },
    weight: { base: 1.2, doubt: 0.8 },
    hitText: 'Hinten fliegt eine Tasche über den Zaun.',
    blockedText: 'Ihr habt den Hinterausgang im Blick.',
  },
  emptyTill: {
    label: 'Sie räumen die Kasse',
    icon: 'coins',
    stake: 'cash',
    damage: 30,
    counters: ['fight', 'bluff'],
    onHit: { resolve: 4 },
    weight: { base: 1, doubt: 0.6 },
    hitText: 'Einer stopft sich das Bargeld in die Jacke.',
    blockedText: 'Die Kasse bleibt, wo sie ist.',
  },
  callFriends: {
    label: 'Sie rufen Verstärkung',
    icon: 'phone',
    drift: { resolve: 8, aggression: 4 },
    counters: ['bluff', 'intimidate'],
    weight: { base: 0.5, resolve: 0.6 },
    hitText: 'Am Telefon: „Kommt her, sofort.“',
    blockedText: 'Das Telefon bleibt in der Tasche.',
  },

  // --- Schuldner ---------------------------------------------------------------------------
  hideMoney: {
    label: 'Er versteckt das Geld',
    icon: 'wallet',
    stake: 'cash',
    damage: 30,
    counters: ['intimidate', 'bluff'],
    onHit: { resolve: 4 },
    weight: { base: 1.3, resolve: 0.8 },
    hitText: 'Ein Umschlag verschwindet hinter dem Tresen.',
    blockedText: 'Ihr habt das Geld im Blick.',
  },
  whine: {
    label: 'Er jammert und bietet einen Teil an',
    icon: 'handshake',
    needs: 'leader',
    drift: { resolve: -6 },
    modifiers: { negotiate: 1.6, intimidate: 1.2, fight: 0.7 },
    weight: { base: 0.6, doubt: 1.2 },
    hitText: '',
    blockedText: '',
  },

  // --- Polizei ----------------------------------------------------------------------------
  search: {
    label: 'Sie wollen in die Taschen sehen',
    icon: 'search',
    stake: 'goods',
    onHit: { resolve: 18, aggression: 4 },
    counters: ['dump'],
    weight: { base: 1.8 },
    hitText: 'Sie finden etwas Verdächtiges. Jetzt bleiben sie dran.',
    blockedText: 'Die Taschen sind leer. Nichts zu sehen.',
  },
  searchVan: {
    label: 'Sie wollen hinten reingucken',
    icon: 'search',
    stake: 'goods',
    onHit: { resolve: 18, aggression: 4 },
    counters: ['papers'],
    weight: { base: 1.8 },
    hitText: 'Die Taschenlampe leuchtet in den Laderaum. Der Beamte runzelt die Stirn.',
    blockedText: 'Die Kisten sehen harmlos aus.',
  },
  radio: {
    label: 'Funk: Verstärkung ist unterwegs',
    icon: 'siren',
    clock: -1,
    weight: { base: 0.6, resolve: 0.7 },
    hitText: 'Aus dem Funkgerät: „Zweiter Wagen ist unterwegs.“',
    blockedText: '',
  },
  askPapers: {
    label: 'Sie wollen Papiere sehen',
    icon: 'idCard',
    modifiers: { negotiate: 1.5, papers: 1.6, bribe: 0.8, flee: 0.8 },
    weight: { base: 1, calm: 0.6 },
    hitText: '',
    blockedText: '',
  },
  grab: {
    label: 'Sie greifen zu',
    icon: 'handcuffs',
    stake: 'people',
    hit: 0.35,
    onHit: { resolve: 5 },
    drift: { aggression: 4 },
    counters: ['negotiate'],
    weight: { base: 0.4, aggression: 1.2, brawl: 1 },
    hitText: 'Ein Griff an den Arm.',
    blockedText: 'Ihr haltet Abstand, Hände sichtbar.',
  },
  hesitate: {
    label: 'Sie zögern',
    icon: 'hourglass',
    drift: { resolve: -8 },
    modifiers: { negotiate: 1.3, bribe: 1.4, papers: 1.2 },
    weight: { base: 0.2, doubt: 1.3 },
    hitText: '',
    blockedText: '',
  },

  // --- Zoll ------------------------------------------------------------------------------
  dog: {
    label: 'Der Spürhund schnüffelt an der Ladung',
    icon: 'search',
    stake: 'goods',
    onHit: { resolve: 20 },
    counters: ['distract'],
    weight: { base: 1.6 },
    hitText: 'Der Hund setzt sich vor die Ladetür und bellt.',
    blockedText: 'Der Hund interessiert sich nur für dein Butterbrot.',
  },
  tarp: {
    label: 'Sie wollen die Plane öffnen',
    icon: 'package',
    stake: 'goods',
    onHit: { resolve: 15, aggression: 4 },
    counters: ['papers', 'bribe'],
    weight: { base: 1.1 },
    hitText: 'Die Plane geht auf. Ein Beamter zählt Kisten.',
    blockedText: 'Die Plane bleibt zu.',
  },
  deliveryNote: {
    label: 'Fragen nach dem Lieferschein',
    icon: 'clipboard',
    modifiers: { papers: 1.6, negotiate: 1.3, bribe: 0.9 },
    weight: { base: 1.1, calm: 0.6 },
    hitText: '',
    blockedText: '',
  },
  callOffice: {
    label: 'Funk ans Hauptzollamt',
    icon: 'siren',
    clock: -1,
    weight: { base: 0.6, resolve: 0.6 },
    hitText: 'Ein Beamter telefoniert. Die Kennzeichen gehen raus.',
    blockedText: '',
  },
};
