// Stimmen der Frankfurter Gangs (Auftrag 39), nach dem Muster von texts.ts: je Anlass fünf eigene Varianten.
// Ton: Kaisersack-Clan wie Durchsagen am Hauptbahnhof, kurz und hart. Mainkapital förmlich, Sie, Bankensprache.
// Die Bembel hessisch, Wirtin mit Bembel. Farbwerker grob, Chemie und Westrand.

import type { GangVoice } from './texts';

export const FRANKFURT_VOICES: Readonly<Record<string, GangVoice>> = {
  // 🚉 Kaisersack-Clan, Dragan Ilić „der Schaffner“: Durchsagen, Fahrkarten, Gleise.
  'ff-bahnhof': {
    warning: [
      'Durchsage für dich: {veedel} ist unser Bahnsteig. Hier steigt keiner ohne Fahrkarte zu.',
      'Der Schaffner hat dich gesehen. In {veedel}. Ohne Ticket.',
      'Dragan hier. In {veedel} verkauft nur, wer bei uns gelöst hat. Du hast nicht gelöst.',
      'Letzte Warnung vor der Abfahrt: Raus aus {veedel}.',
      'Zwischen Kaiserstraße und Gleis 1 gehört alles uns. Auch {veedel}. Merk dir das.',
    ],
    threat: [
      'Fahrkarte für {veedel}: {tribute} die Woche. Schwarzfahrer werden rausgeworfen.',
      'Der Schaffner kassiert {tribute} pro Woche. Dann darfst du in {veedel} mitfahren.',
      '{tribute} wöchentlich, Dauerkarte für {veedel}. Ohne gibt es Ärger am Bahnsteig.',
      'Dragan. {tribute} die Woche. Das ist der Tarif, und der Tarif gilt für alle.',
      'Wer am Bahnhof verkauft, zahlt Bahnhofspreise. {tribute} pro Woche.',
    ],
    war: [
      'Durchsage: Für dich fährt hier kein Zug mehr. Nie wieder.',
      'Der Schaffner hat dich aus dem Fahrplan gestrichen. Ab jetzt holen wir dich.',
      'Endstation. Alle aussteigen, du zuerst.',
      'Das Bahnhofsviertel hat dich auf dem Schirm. Jede Ecke, jede Nacht.',
      'Dragan sagt: Zug abgefahren. Jetzt kommen wir.',
    ],
    raidWon: [
      'Diesmal bist du durchgekommen. Der nächste Zug ist voller.',
      'Glück am Bahnsteig. Das hat man nicht jeden Tag.',
      'Meine Leute sind angeschlagen. Der Fahrplan steht trotzdem.',
      'Notiert. Am Hauptbahnhof vergisst man kein Gesicht.',
      'Du hast gewonnen. Einmal. Der Bahnhof hat viele Gleise.',
    ],
    raidLost: [
      'Fahrkartenkontrolle. Du hattest keine. Ware eingezogen.',
      'So läuft das an der Kaiserstraße. Danke für die Spende.',
      'Wir haben abgeräumt. Nächste Kontrolle kommt bestimmt.',
      'Erhöhtes Beförderungsentgelt bezahlt. Mit deiner Ware.',
      'Ein Abend im Bahnhofsviertel. Kostet immer mehr, als man denkt.',
    ],
    attacked: [
      'Du hast einen von uns angefasst. Jetzt kommt der ganze Bahnhof.',
      'Dragan ist nicht mehr freundlich. Das merkst du bald.',
      'Gleis 1 bis 24, überall stehen jetzt unsere Leute. Für dich.',
      'Wer den Schaffner angreift, fährt nie wieder irgendwohin.',
      'Das war ein Fehler. Am Bahnhof bezahlt man Fehler sofort.',
    ],
    snitch: [
      'Die Bundespolizei war da. Mit deinem Namen. Jetzt steht er auch bei uns.',
      'Einer hat gequatscht. Am Bahnhof hört man alles.',
      'Verpfiffen. Von dir. Dragan nimmt das persönlich.',
      'Die Wache in der B-Ebene hat einen Tipp gekriegt. Wir wissen von wem.',
      'Petzen am Bahnhof. Das spricht sich schneller rum als jede Verspätung.',
    ],
    tributeDue: [
      'Neue Woche, neue Fahrkarte: {tribute}.',
      'Der Schaffner kassiert: {tribute}.',
      'Dragan hier. {tribute} sind fällig. Bar, am Gleis.',
      '{tribute}, wie jede Woche. Der Bahnhof schläft nie.',
      'Kontrolle. {tribute}, bitte.',
    ],
    protectionRefused: [
      'Diese Woche zahlt der Bahnhof nicht. Komm und hol es dir.',
      'Kein Geld. Der Schaffner kontrolliert selbst.',
      'Wir zahlen keinem. Wir sind die Kontrolle.',
      'Schutzgeld? Am Bahnhof schützen wir uns selbst.',
      'Abgelehnt. Fahrkarte ungültig.',
    ],
    offer: [
      'Hab {amount} übrig, frisch angekommen. {price}, abholen in {veedel}. Bevor der Zug weg ist.',
      'Dragan. {amount} für {price}. Schließfach in {veedel}, ich schick dir die Nummer.',
      'Aus der letzten Lieferung: {amount}, {price}. In {veedel}, frag nach dem Schaffner.',
      'Sonderangebot am Bahnsteig: {amount} für {price}. {veedel}, heute noch.',
      'Restposten: {amount}, {price}. Abholung {veedel}, Hintereingang.',
    ],
    allianceOffer: [
      '{enemy} will an unsere Gleise. {price}, und du fährst mit uns.',
      'Dragan bietet: zusammen gegen {enemy}. {price}.',
      'Wir brauchen Leute gegen {enemy}. {price}, dann bist du im Zug.',
      'Der Bahnhof gegen {enemy}. Dein Ticket kostet {price}.',
      'Gemeinsam schmeißen wir {enemy} raus. Kostet dich {price}.',
    ],
    intimidation: [
      'Meine Leute stehen jetzt {atSpot}. Fahrkartenkontrolle für jeden Kunden.',
      'Dragan hier. {AtSpot} wird ab heute kontrolliert. Deine Kunden haben keine Karte.',
      'Dein Spot {spot} ist jetzt unser Bahnsteig.',
      '{AtSpot} stehen jetzt meine Jungs. Wer kauft, kauft bei uns.',
      'Durchsage {atSpot}: Hier verkauft der Kaisersack.',
    ],
    tipOff: [
      'Hab der Wache am Hauptbahnhof was über {veedel} erzählt. Viel Spaß.',
      'Die Bundespolizei weiß jetzt, was in {veedel} am Laufen ist.',
      'Dragan hat telefoniert. {veedel} wird heiß.',
      'Ein Wort in der B-Ebene, ein Bulle hört zu. {veedel}.',
      'Die Streife schaut jetzt öfter in {veedel}. Schöne Grüße vom Bahnhof.',
    ],
    blackmail: [
      'Ich kenn deinen {warehouse}. {amount}, sonst kennt ihn die Wache auch.',
      'Dragan. {amount} oder die Bullen kriegen den {warehouse}.',
      'Nette Adresse, dein {warehouse}. {amount} und ich vergesse sie.',
      '{amount}, dann fährt keine Streife zum {warehouse}.',
      'Für {amount} hab ich nie was vom {warehouse} gehört. Durchsage beendet.',
    ],
    warnRival: [
      'Tipp vom Bahnsteig: {enemy} will an dich ran.',
      'Dragan hier. {enemy} plant was. Pass auf.',
      'Hab am Kiosk gehört: {enemy} kommt zu dir.',
      '{enemy} sammelt Leute. Gegen dich, sagen die Schaffner.',
      'Kleine Durchsage unter Nachbarn: {enemy} sucht Stress.',
    ],
    favor: [
      'Brauch ein paar Schließfächer. Deine. {amount}, drei Tage.',
      'Dragan. Kannst du was für uns bunkern? {amount}.',
      'Der Bahnhof ist zu heiß gerade. Nimm unser Zeug, kriegst {amount}.',
      'Ein bezahlter Gefallen: {amount} fürs Lagern.',
      'Wir brauchen deinen Keller. {amount}, keine Fragen.',
    ],
    warAsk: [
      'Kaisersack hier. Wir werfen {enemy} aus {veedel}. Fährst du mit?',
      'Heute Nacht räumen wir bei {enemy} auf. Wer hilft, hat am Bahnhof immer einen Platz.',
      '{enemy} hat in {veedel} nichts verloren. Hilf uns, und du hast hier Kredit.',
      'Ich frag einmal: Gegen {enemy}, bist du dabei? Ware oder Leute.',
      'Der Bahnhof geht auf {enemy} los. Wer jetzt nicht einsteigt, bleibt am Gleis stehen.',
    ],
  },
  // 💼 Mainkapital, Dr. Konstantin Wehrle: förmlich, Sie, Bankensprache, droht mit Anwälten und Kontakten.
  'ff-westend': {
    warning: [
      'Sehr geehrte Damen und Herren, Ihre Aktivitäten in {veedel} sind mit unserem Geschäftsmodell nicht vereinbar.',
      'Dr. Wehrle. Wir haben {veedel} geprüft und sehen dort keinen Platz für einen weiteren Marktteilnehmer.',
      'Eine freundliche Mitteilung: In {veedel} gelten unsere Konditionen. Sie erfüllen sie nicht.',
      'Wir bitten Sie, Ihre Position in {veedel} zeitnah aufzulösen. Ohne Vorfälligkeitsentschädigung.',
      'Mainkapital weist darauf hin, dass {veedel} kein Wachstumsmarkt für Sie ist.',
    ],
    threat: [
      'Für Ihre Präsenz in {veedel} berechnen wir eine Verwaltungsgebühr von {tribute} pro Woche.',
      'Dr. Wehrle. Unser Angebot: {tribute} wöchentlich, dafür bleibt {veedel} für Sie ruhig.',
      'Die Konditionen sind nicht verhandelbar: {tribute} pro Woche.',
      'Betrachten Sie {tribute} pro Woche als Versicherungsprämie. Die Alternative ist deutlich teurer.',
      'Wir erwarten {tribute} wöchentlich. Unsere Kanzlei hat das bereits vorbereitet.',
    ],
    war: [
      'Wir beenden die Geschäftsbeziehung. Mit allen Mitteln, die uns zur Verfügung stehen.',
      'Dr. Wehrle. Ab heute arbeiten unsere Kontakte gegen Sie. Alle.',
      'Ihre Position wird abgewickelt. Sie werden das in jeder Bilanz merken.',
      'Mainkapital hat Sie auf die Liste gesetzt. Es ist keine gute Liste.',
      'Wir haben genug Geld, um Sie zu ruinieren. Und Geduld.',
    ],
    raidWon: [
      'Ein kurzfristiger Verlust. Wir denken langfristig.',
      'Respekt. Wir passen unsere Strategie an.',
      'Das war teuer für uns. Es wird teurer für Sie.',
      'Wir haben den Vorgang dokumentiert. Für später.',
      'Gratulation. Die Aufsicht hat ein gutes Gedächtnis, wir auch.',
    ],
    raidLost: [
      'Wir haben Ihre Bestände übernommen. Betrachten Sie es als Restrukturierung.',
      'Ein bedauerlicher Wertverlust für Sie. Für uns eine Chance.',
      'Die Transaktion ist abgeschlossen. Zu unseren Gunsten.',
      'Sie haben unterschätzt, wer im Westend wohnt.',
      'Ware und Geld wurden umgebucht. Auf unser Konto.',
    ],
    attacked: [
      'Sie haben einen unserer Mitarbeiter angegriffen. Das hat Konsequenzen, juristische und andere.',
      'Dr. Wehrle ist enttäuscht. Enttäuschung ist bei uns teuer.',
      'Ein Angriff auf Mainkapital ist ein Angriff auf sehr viele Freunde.',
      'Wir werden das nicht vor Gericht klären. Leider für Sie.',
      'Sie haben eine Grenze überschritten. Wir ziehen jetzt eine neue.',
    ],
    snitch: [
      'Sie haben mit der Polizei gesprochen. Wir sprechen mit dem Präsidium. Öfter als Sie.',
      'Ein Hinweis aus Ihrer Richtung. Unsere Anwälte haben ihn gelesen, bevor die Polizei es tat.',
      'Wir wissen, wer geredet hat. Das kostet Sie Vertrauen, und Vertrauen ist unsere Währung.',
      'Ihre Aussage liegt uns vor. Wie praktisch.',
      'Verrat ist ein schlechtes Geschäftsmodell. Sie werden das lernen.',
    ],
    tributeDue: [
      'Ihre wöchentliche Gebühr wird fällig: {tribute}.',
      'Dr. Wehrle. Zahlungserinnerung über {tribute}.',
      'Fälligkeit heute: {tribute}. Wir bitten um pünktliche Valuta.',
      '{tribute}, wie vereinbart. Bar, bitte.',
      'Die Rate über {tribute} ist fällig.',
    ],
    protectionRefused: [
      'Wir verzichten diese Woche auf Ihre Zahlung. Wir brauchen sie nicht.',
      'Mainkapital zahlt keine Schutzgebühren. Wir sind abgesichert.',
      'Abgelehnt. Unsere Rücklagen sind beträchtlich.',
      'Eine Schutzgebühr? Wir haben eine Rechtsabteilung.',
      'Kein Bedarf. Unsere Absicherung ist besser als Ihre.',
    ],
    offer: [
      'Wir haben {amount} Premiumware abzugeben. {price}, Übergabe diskret in {veedel}.',
      'Dr. Wehrle. {amount} zu {price}. Abholung in {veedel}, Tiefgarage.',
      'Ein Angebot unter Geschäftsleuten: {amount} für {price}, in {veedel}.',
      'Überschussbestände: {amount}, {price}. Lieferung nach {veedel} möglich.',
      'Exklusiv für Sie: {amount} zu {price}. Befristet gültig, in {veedel}.',
    ],
    allianceOffer: [
      '{enemy} stört den Markt. Eine Partnerschaft gegen sie kostet Sie {price}.',
      'Dr. Wehrle schlägt eine Kooperation gegen {enemy} vor. Einstieg: {price}.',
      'Gemeinsam bereinigen wir den Markt um {enemy}. Ihre Einlage: {price}.',
      'Eine strategische Allianz gegen {enemy}. Die Konditionen: {price}.',
      'Wir bieten Ihnen eine Beteiligung an der Abwicklung von {enemy}. {price}.',
    ],
    intimidation: [
      'Unsere Mitarbeiter stehen jetzt {atSpot}. Ihre Kunden werden das verstehen.',
      'Dr. Wehrle. {AtSpot} ist ab heute unser Sicherheitsdienst präsent.',
      'Ihr Spot {spot} steht ab sofort unter unserer Aufsicht.',
      '{AtSpot} prüfen wir jetzt jede Transaktion.',
      'Wir haben {atSpot} Präsenz gezeigt. Diskret, aber deutlich.',
    ],
    tipOff: [
      'Ein Bekannter im Polizeipräsidium an der Adickesallee interessiert sich jetzt für {veedel}.',
      'Dr. Wehrle hat ein Gespräch beim Abendessen geführt. Es ging um {veedel}.',
      'Die Polizei hat Hinweise zu {veedel} erhalten. Aus guter Quelle.',
      'Ihre Geschäfte in {veedel} sind jetzt aktenkundig.',
      'Wir haben {veedel} der zuständigen Stelle gemeldet. Ganz formal.',
    ],
    blackmail: [
      'Uns ist die Adresse Ihres {warehouse} bekannt. Für {amount} bleibt das so.',
      'Dr. Wehrle. {amount}, oder die Unterlagen zum {warehouse} gehen an die Staatsanwaltschaft.',
      'Ihr {warehouse} ist ein Risiko. Wir versichern es für {amount}.',
      'Für {amount} vergessen wir den {warehouse}. Vertraglich.',
      '{amount}, und der {warehouse} taucht in keinem Bericht auf.',
    ],
    warnRival: [
      'Eine Information zu Ihrem Vorteil: {enemy} plant gegen Sie.',
      'Dr. Wehrle. Wir beobachten, dass {enemy} Leute sammelt. Gegen Sie.',
      'Marktbeobachtung: {enemy} wird aggressiv. Ziel sind Sie.',
      'Wir raten zur Vorsicht. {enemy} bewegt sich.',
      'Ein Hinweis unter Marktteilnehmern: {enemy} sucht Streit.',
    ],
    favor: [
      'Wir benötigen kurzfristig Lagerfläche. {amount} für drei Tage.',
      'Dr. Wehrle. Ein diskreter Gefallen: Sie lagern, wir zahlen {amount}.',
      'Unsere Bestände müssen kurz verschwinden. {amount} Aufwandsentschädigung.',
      'Ein bezahlter Dienst: {amount} für Verwahrung.',
      'Wir mieten Ihren Keller. {amount}, ohne Vertrag.',
    ],
    warAsk: [
      'Mainkapital trennt sich von {enemy} in {veedel}. Möchten Sie sich beteiligen?',
      'Dr. Wehrle. Wir bereinigen {veedel} um {enemy}. Ihre Unterstützung wird sich lohnen.',
      '{enemy} hat in {veedel} keine Zukunft. Helfen Sie uns, und Sie haben im Westend Freunde.',
      'Eine einmalige Anfrage: Gegen {enemy}, mit Ware oder Personal?',
      'Wir übernehmen {veedel} von {enemy}. Wer jetzt investiert, wird beteiligt.',
    ],
  },
  // 🍺 Die Bembel, Gisela „Mutter Bembel“ Hartmann: hessisch, Wirtin, Apfelwein.
  'ff-sachsenhausen': {
    warning: [
      'Ei gude. In {veedel} schenkt nur aus, wer bei der Mutter Bembel gefragt hat. Du hast net gefragt.',
      'Bub, {veedel} is mei Wirtschaft. Da stellt sich keiner ungefragt an die Theke.',
      'Gisela hier. Ich hab dich in {veedel} gesehen. Des gefällt mir net.',
      'In {veedel} kennt jeder Wirt mei Nummer. Und jetzt kennt er auch dei Gesicht.',
      'Lass {veedel} in Ruh. Sonst gibt es keinen Äppler mehr für dich, und auch sonst nix.',
    ],
    threat: [
      'Wer in {veedel} verkauft, zahlt an die Theke. {tribute} die Woche.',
      'Gisela. {tribute} pro Woche, dann darfst du in {veedel} mit am Tisch sitzen.',
      '{tribute} wöchentlich. So macht des jede Wirtschaft in der Gass.',
      'Des kost {tribute} die Woche, Bub. Billiger wird es net.',
      'Die Mutter Bembel will {tribute} pro Woche. Und die Mutter Bembel kriegt, was sie will.',
    ],
    war: [
      'Jetzt is Schluss mit lustig. Kein Wirt in Sachsenhausen lässt dich mehr rein.',
      'Die Bembel sind leer. Für dich gibt es nur noch Ärger.',
      'Gisela hat die Geduld verloren. Und die findet sie so schnell net wieder.',
      'Ab heute bist du in jeder Wirtschaft am Main unerwünscht. Und das spricht sich rum.',
      'Feierabend für dich. Stühle hoch, Licht aus.',
    ],
    raidWon: [
      'Na gut, die Runde geht an dich. Die nächste schenk ich ein.',
      'Respekt, Bub. Aber der Abend is noch lang.',
      'Mei Leut sind angeschlagen. Die Gass is es net.',
      'Hab ich mir gemerkt. Die Mutter Bembel vergisst nix.',
      'Glück gehabt. Des passiert dir in Sachsenhausen net zweimal.',
    ],
    raidLost: [
      'Des war die Zeche. Mit Trinkgeld.',
      'Rausgeworfen, wie einer, der net zahlt.',
      'Wir haben abgeräumt. Wie nach jedem Junggesellenabschied.',
      'Dei Ware steht jetzt bei uns im Keller. Neben dem Äppler.',
      'So geht des in der Gass. Bezahlt hast du.',
    ],
    attacked: [
      'Du hast einen von meinen Wirten angefasst. Jetzt kommt ganz Sachsenhausen.',
      'Gisela is net amüsiert. Und wenn Gisela net amüsiert is, gibt es Scherben.',
      'Des war mei Wirtschaft. Jetzt wird dei Laden Kleinholz.',
      'Am Main schlägt man net ungestraft zu, Bub.',
      'Du hast der Mutter Bembel den Bembel umgeschmissen. Des wäscht man net mit Wasser ab.',
    ],
    snitch: [
      'Du hast die Polizei in die Gass geschickt? Die trinken bei uns, Bub.',
      'Ein Petzer in Sachsenhausen. Des hat es lang net gegeben.',
      'Wir wissen, wer geredet hat. Jeder Wirt hat Ohren.',
      'Verpfiffen. Von dir. Des nehm ich persönlich.',
      'Die Bullen waren da. Dein Name stand auf ihrem Bierdeckel.',
    ],
    tributeDue: [
      'Neue Woche, neue Zeche: {tribute}.',
      'Die Mutter Bembel kassiert: {tribute}.',
      'Gisela hier. {tribute} sind fällig. Bar an der Theke.',
      '{tribute}, wie jede Woche. Anschreiben gibt es net.',
      'Zahltag in der Gass. {tribute}.',
    ],
    protectionRefused: [
      'Die Woch zahlt die Wirtschaft net. Komm her und hol es dir.',
      'Kein Geld. Die Mutter Bembel sagt Nein.',
      'Die Bembel zahlen keinem was. Mir sind uns selbst genug.',
      'Schutzgeld? Mir sind der Schutz, Bub.',
      'Abgelehnt. Wie ein Gast ohne Geld.',
    ],
    offer: [
      'Ich hab {amount} über, gute Ware. {price}, abholen in {veedel}. Wart net zu lang.',
      'Gisela. {amount} für {price}. Hinterhof in {veedel}.',
      'Aus dem Keller: {amount}, {price}. In {veedel}, frag nach der Wirtin.',
      'Des Fest war kleiner als gedacht. {amount} übrig, {price}. {veedel}.',
      'Angebot vom Tresen: {amount} für {price}. Nur heut, in {veedel}.',
    ],
    allianceOffer: [
      '{enemy} macht uns die Gass streitig. {price}, und du sitzt mit uns am Tisch.',
      'Gisela bietet: zusammen gegen {enemy}. {price}.',
      'Mir brauchen Leut gegen {enemy}. Du hast welche. {price}, dann sind mir Freunde.',
      'Sachsenhausen gegen {enemy}. Dei Platz am Tisch kost {price}.',
      'Gemeinsam schmeißen mir {enemy} aus der Wirtschaft. Kost dich {price}.',
    ],
    intimidation: [
      'Mei Leut sitzen jetzt {atSpot}. Wer kauft, kauft bei uns.',
      'Gisela hier. {AtSpot} schenkt ab heut die Mutter Bembel aus.',
      'Dein Spot {spot} hat jetzt einen neuen Wirt. Uns.',
      '{AtSpot} stehen jetzt mei Türsteher. Deine Kunden kommen net rein.',
      '{AtSpot} gibt es ab heut nur noch Äppler. Und unser Zeug.',
    ],
    tipOff: [
      'Hab dem Revier was über {veedel} erzählt. Die trinken bei mir, weißt du.',
      'Die Polizei weiß jetzt Bescheid, was in {veedel} los is.',
      'Gisela hat telefoniert. {veedel} wird heiß.',
      'Ein Wort an der Theke, ein Bulle hört zu. {veedel}, Bub.',
      'Schöne Grüße vom Main. Die Streife fährt jetzt öfter durch {veedel}.',
    ],
    blackmail: [
      'Ich kenn deinen {warehouse}. {amount}, sonst kennt ihn das Revier auch.',
      'Gisela. {amount} oder die Bullen kriegen den {warehouse}.',
      'Nette Lage, dein {warehouse}. {amount} und ich vergess die Hausnummer.',
      '{amount}, dann bleibt dei {warehouse} unser Geheimnis.',
      'Für {amount} hab ich vom {warehouse} nie was gehört. Ehrenwort.',
    ],
    warnRival: [
      'Tipp von der Theke: {enemy} will an dich ran.',
      'Gisela hier. {enemy} plant was. Pass auf, Bub.',
      'Hab in der Gass gehört: {enemy} kommt zu dir.',
      '{enemy} trommelt Leut zusammen. Gegen dich.',
      'Kleiner Gefallen unter Nachbarn: {enemy} sucht Ärger.',
    ],
    favor: [
      'Brauch Platz für ein paar Kisten. {amount}, drei Tag.',
      'Gisela. Kannst du was für uns lagern? {amount}.',
      'Die Gass is zu heiß. Nimm unser Zeug, kriegst {amount}.',
      'Ein Gefallen unter Wirtsleut, bezahlt: {amount}.',
      'Mir brauchen deinen Keller, Bub. {amount}.',
    ],
    warAsk: [
      'Die Bembel räumen {enemy} aus {veedel}. Sitzt du mit am Tisch?',
      'Heut Nacht schenken mir {enemy} was ein. Wer hilft, trinkt bei uns umsonst.',
      '{enemy} hat in {veedel} nix verloren. Hilf uns, und Sachsenhausen vergisst es dir net.',
      'Ich frag einmal: Gegen {enemy}, bist du dabei? Ware oder Leut.',
      'Die Mutter Bembel geht auf {enemy} los. Wer jetzt kneift, kriegt Hausverbot. Für immer.',
    ],
  },
  // ⚗ Farbwerker, Erkan „Chemie“ Doğan: grob, vom Westrand, Chemie und Cargo City.
  'ff-hoechst': {
    warning: [
      'Chemie hier. {veedel} ist unser Werksgelände. Unbefugten ist der Zutritt verboten.',
      'Du riechst nach Ärger. In {veedel}. Hau ab, bevor es reagiert.',
      'Erkan. In {veedel} verkauft nur, wer bei uns Schicht hat. Du hast keine.',
      'Warnschild für dich: {veedel}. Giftig für Fremde.',
      'Die Farbwerker haben dich in {veedel} gesehen. Nächstes Mal sehen sie dich nicht mehr gehen.',
    ],
    threat: [
      'Werksgebühr für {veedel}: {tribute} die Woche. Sonst explodiert was.',
      'Chemie will {tribute} pro Woche. Dann bleibt {veedel} für dich stabil.',
      '{tribute} wöchentlich. So funktioniert die Formel.',
      'Erkan. {tribute} die Woche. Ohne Zahlung kippt die Reaktion.',
      '{tribute} pro Woche, oder wir machen in {veedel} einen Störfall.',
    ],
    war: [
      'Störfall. Ab jetzt sind wir hinter dir her, überall.',
      'Chemie hat genug. Jetzt wird es ätzend für dich.',
      'Die Farbwerker kommen raus aus Höchst. Für dich.',
      'Du hast die Reaktion gestartet. Jetzt brennt es.',
      'Erkan sagt: Schichtwechsel. Ab heute bist du die Arbeit.',
    ],
    raidWon: [
      'Diesmal hat es dich nicht erwischt. Wir mischen neu.',
      'Glück gehabt. Die nächste Ladung ist stärker.',
      'Meine Jungs sind verbrannt. Der Industriepark hat mehr.',
      'Notiert. In Höchst vergisst man nichts.',
      'Du hast gewonnen. Die Halbwertszeit davon ist kurz.',
    ],
    raidLost: [
      'Wir haben dich abgefüllt. Deine Ware gehört jetzt uns.',
      'Das war eine saubere Reaktion. Für uns.',
      'Abgeräumt. Wie in der Cargo City, wenn keiner hinschaut.',
      'Ware weg, Leute weg. So läuft das am Westrand.',
      'Danke für die Lieferung. Wir hätten sie auch so genommen.',
    ],
    attacked: [
      'Du hast einen Farbwerker angefasst. Jetzt kommt die ganze Schicht.',
      'Chemie ist sauer. Und sauer ist bei uns ätzend.',
      'Das war ein Fehler. In Höchst zahlt man Fehler doppelt.',
      'Du hast in den falschen Tank gegriffen.',
      'Erkan kommt persönlich. Das hat noch keiner überlebt, ohne zu lernen.',
    ],
    snitch: [
      'Du hast die Bullen nach Höchst geschickt? Die kennen den Weg gar nicht.',
      'Einer hat gequatscht. Am Westrand redet man nicht.',
      'Verpfiffen. Von dir. Chemie nimmt das persönlich.',
      'Der Zoll in der Cargo City hat einen Tipp gekriegt. Wir wissen, woher.',
      'Petzen ist giftig. Für dich.',
    ],
    tributeDue: [
      'Neue Woche, neue Gebühr: {tribute}.',
      'Chemie kassiert: {tribute}.',
      'Erkan hier. {tribute} sind fällig. Bar, am Werkstor.',
      '{tribute}, wie jede Woche. Die Anlage läuft immer.',
      'Lohntag für uns. {tribute}.',
    ],
    protectionRefused: [
      'Die Farbwerker zahlen nicht. Komm nach Höchst und hol es dir.',
      'Kein Geld. Chemie sagt Nein.',
      'Wir zahlen keinem. Wir sind gefährlich genug.',
      'Schutzgeld? Wir sind der Gefahrstoff.',
      'Abgelehnt. Schicht vorbei.',
    ],
    offer: [
      'Hab {amount} übrig, vom Band gefallen. {price}, abholen in {veedel}.',
      'Erkan. {amount} für {price}. Am Werkstor in {veedel}.',
      'Aus der Cargo City: {amount}, {price}. In {veedel}, frag nach Chemie.',
      'Restcharge: {amount} für {price}. {veedel}, heute noch.',
      'Billig vom Westrand: {amount}, {price}. Abholung {veedel}.',
    ],
    allianceOffer: [
      '{enemy} will an unser Werk. {price}, und du stehst mit uns am Tor.',
      'Chemie bietet: zusammen gegen {enemy}. {price}.',
      'Wir brauchen Leute gegen {enemy}. {price}, dann gehörst du zur Schicht.',
      'Höchst gegen {enemy}. Dein Werksausweis kostet {price}.',
      'Gemeinsam lösen wir {enemy} auf. Kostet dich {price}.',
    ],
    intimidation: [
      'Meine Jungs stehen jetzt {atSpot}. Wer kauft, kauft bei Chemie.',
      'Erkan hier. {AtSpot} ist ab heute Werksgelände.',
      'Dein Spot {spot} gehört jetzt zur Schicht. Unserer.',
      '{AtSpot} stehen jetzt die Farbwerker. Deine Kunden riechen das.',
      'Warnschild {atSpot}: Betreten nur für Farbwerker.',
    ],
    tipOff: [
      'Hab den Bullen was über {veedel} erzählt. Viel Spaß mit der Razzia.',
      'Die Polizei hat jetzt eine Probe aus {veedel}.',
      'Chemie hat telefoniert. {veedel} wird heiß.',
      'Ein Anruf vom Werkstelefon, und {veedel} kocht.',
      'Schöne Grüße aus Höchst. Die Streife ist jetzt öfter in {veedel}.',
    ],
    blackmail: [
      'Ich kenn deinen {warehouse}. {amount}, sonst kennt ihn der Zoll auch.',
      'Erkan. {amount} oder die Bullen kriegen den {warehouse}.',
      'Dein {warehouse} ist eine tickende Zeitbombe. {amount} und ich entschärfe sie.',
      '{amount}, dann bleibt der {warehouse} dicht wie ein Tank.',
      'Für {amount} hab ich vom {warehouse} nie was gerochen.',
    ],
    warnRival: [
      'Tipp vom Werkstor: {enemy} will an dich ran.',
      'Erkan hier. {enemy} mischt was gegen dich zusammen.',
      'Hab in der Cargo City gehört: {enemy} kommt zu dir.',
      '{enemy} rührt Leute zusammen. Gegen dich.',
      'Kleine Warnung unter Nachbarn: {enemy} sucht Stress.',
    ],
    favor: [
      'Brauch Platz für ein paar Fässer. {amount}, drei Tage.',
      'Chemie. Kannst du was für uns lagern? {amount}.',
      'Höchst ist zu heiß gerade. Nimm unser Zeug, kriegst {amount}.',
      'Ein bezahlter Gefallen vom Westrand: {amount}.',
      'Wir brauchen deine Halle. {amount}, keine Fragen.',
    ],
    warAsk: [
      'Farbwerker hier. Wir räumen {enemy} aus {veedel}. Bist du dabei?',
      'Heute Nacht lösen wir {enemy} auf. Wer hilft, hat in Höchst Freunde.',
      '{enemy} hat in {veedel} nichts verloren. Hilf uns, und die Cargo City steht dir offen.',
      'Ich frag einmal: Gegen {enemy}, mit Ware oder Leuten?',
      'Chemie geht auf {enemy} los. Wer jetzt nicht mitmacht, steht im Weg.',
    ],
  },
};
