// Stimmen der Berliner Gangs (Auftrag 37), gleiche Anlässe und Platzhalter wie in texts.ts.
// Ton: Die Türsteher knapp und cool (Gästeliste, Tür, Wochenende). Kotti-Familie: Familie, Respekt, der Onkel spricht.
// Leo-Gang: Berliner Schnauze, rotzig, laut. Kudamm-Kreis: höflich, gebildet, kalt.

import type { GangVoice } from './texts';

export const GANG_VOICES_BERLIN: Readonly<Record<string, GangVoice>> = {
  // 🎧 Die Türsteher, Goran „Gästeliste“ Vuković: knapp, cool, Club-Tür.
  'be-tuer': {
    warning: [
      'Heute nicht. {veedel} ist unsere Tür, und du bist nicht eingeladen.',
      'Goran hier. In {veedel} entscheiden wir, wer reinkommt. Dich haben wir nicht entschieden.',
      'Du verkaufst in {veedel}? Ohne Stempel? Mutig.',
      'Die Schlange in {veedel} gehört uns. Wer drin verkauft, fragt vorher.',
      'Kleiner Hinweis von der Tür: In {veedel} bist du zu laut. Mach leiser oder geh.',
    ],
    threat: [
      '{tribute} pro Woche, dann steht dein Name auf der Liste. Für {veedel}.',
      'Gästeliste kostet. {tribute} die Woche, sonst bleibt {veedel} für dich zu.',
      'Goran will {tribute} wöchentlich. Dafür lassen wir dich in {veedel} in Ruhe.',
      'Eintritt für Verkäufer: {tribute}. Pro Woche. Keine Ausnahmen.',
      '{tribute} jede Woche, wie jeder Club in {veedel}. Du bist auch nur ein Club.',
    ],
    war: [
      'Du bist raus. Aus jedem Club, an jeder Tür. Ab jetzt kommen wir zu dir.',
      'Goran hat deinen Namen gestrichen. Und dann dein Gesicht notiert.',
      'Die Tür ist zu. Für immer. Wir sehen uns draußen.',
      'Ab heute keine Gästeliste mehr für dich. Nur noch die andere Liste.',
      'Wochenende ist vorbei für dich. Montag kommen wir.',
    ],
    raidWon: [
      'Du hast die Tür gehalten. Eine Nacht. Die nächste wird länger.',
      'Okay. Du kannst was. Merken wir uns.',
      'Meine Jungs brauchen eine Pause. Danach kommen mehr.',
      'Glück gehabt. Freitag ist bald wieder.',
      'Respekt. Ist trotzdem nicht deine Tür.',
    ],
    raidLost: [
      'Rausgeworfen. So läuft das bei uns um sechs Uhr früh.',
      'Wir haben aufgeräumt. Deine Ware war im Weg.',
      'Das war die Sperrstunde. Gibt es in Berlin eigentlich nicht. Für dich schon.',
      'Kurzer Besuch, langer Abend für dich. Wir haben mitgenommen, was rumlag.',
      'Ausweiskontrolle. Du bist durchgefallen.',
    ],
    attacked: [
      'Du hast einen von der Tür angefasst. Jetzt kommen alle.',
      'Goran ist wach. Das ist schlecht für dich.',
      'Du greifst die Tür an? Am Wochenende? Wirklich?',
      'Das war unser Laden. Jetzt ist es dein Problem.',
      'Keiner rempelt meine Jungs an. Keiner.',
    ],
    snitch: [
      'Die Polizei war an der Tür. Mit deinem Tipp. Wir haben deinen Namen auch.',
      'Verpfiffen. Ausgerechnet du. Die Tür hört alles.',
      'Wer petzt, kommt nie wieder rein. Nirgends.',
      'Die Bullen haben gefragt. Wir wissen, wer ihnen die Antwort gegeben hat.',
      'Goran nimmt sowas persönlich. Und er vergisst keine Gesichter.',
    ],
    tributeDue: [
      'Neue Woche. {tribute} für die Liste.',
      'Goran kassiert. {tribute}, bar.',
      '{tribute}. Die Tür wartet.',
      'Freitag ist Zahltag: {tribute}.',
      'Wie jede Woche: {tribute}, dann bleibt dein Name drauf.',
    ],
    protectionRefused: [
      'Kein Geld diese Woche. Die Tür zahlt nicht.',
      'Schutz? Wir sind die Tür. Wir schützen uns selbst.',
      'Abgelehnt. Wie Leute in Turnschuhen.',
      'Die Türsteher zahlen nicht mehr. Hol es dir, wenn du kannst.',
      'Goran sagt Nein. Mehr gibt es nicht zu sagen.',
    ],
    offer: [
      'Nach der Nacht ist was übrig: {amount} für {price}. Hinterhof in {veedel}.',
      'Goran. {amount}, {price}. Seiteneingang, {veedel}.',
      'Garderobe hat {amount} gefunden. {price}. {veedel}, heute noch.',
      'Weniger Gäste als gedacht. {amount} für {price}, abholen in {veedel}.',
      'Restposten vom Wochenende: {amount}, {price}. In {veedel}, frag an der Tür.',
    ],
    allianceOffer: [
      '{enemy} drängelt an unserer Tür. {price}, und du stehst mit uns.',
      'Goran bietet: du und wir gegen {enemy}. Kostet {price}.',
      'Wir brauchen mehr Leute vor {enemy}. {price}, dann gehörst du dazu.',
      'Zusammen machen wir {enemy} die Tür zu. Dein Eintritt: {price}.',
      'Die Tür und du gegen {enemy}. {price}, dann reden wir weiter.',
    ],
    intimidation: [
      'An deinem {spot} steht jetzt einer von uns. Deine Kunden kommen nicht durch.',
      'Goran hier. Am {spot} ist jetzt Einlass nach Gesicht. Deine Kunden haben das falsche.',
      'Der {spot} hat ab heute eine Tür. Unsere.',
      'Am {spot} läuft jetzt unsere Liste. Deine Leute stehen nicht drauf.',
      'Heute ist am {spot} geschlossene Gesellschaft.',
    ],
    tipOff: [
      'Ein Bulle hat am Wochenende bei uns gefeiert. Jetzt weiß er, was in {veedel} läuft.',
      'Goran hat einen Tipp gegeben. {veedel} wird ungemütlich.',
      'Die Polizei hat nach {veedel} gefragt. Wir waren hilfsbereit.',
      'In {veedel} gibt es bald mehr Streife. Danke uns später.',
      'Kleiner Anruf, große Wirkung. {veedel}, viel Spaß.',
    ],
    blackmail: [
      'Dein {warehouse}, wir kennen die Adresse. {amount}, und wir vergessen sie.',
      'Goran. {amount}, sonst steht die Polizei vor deinem {warehouse}.',
      'Nettes Lager, der {warehouse}. {amount}, dann bleibt es nett.',
      '{amount} und der {warehouse} bleibt unser kleines Geheimnis.',
      'Für {amount} hat an der Tür keiner je vom {warehouse} gehört.',
    ],
    warnRival: [
      'Von der Tür: {enemy} will an dich ran.',
      'Goran hier. {enemy} sammelt Leute. Gegen dich.',
      'In der Schlange gehört: {enemy} kommt zu dir.',
      '{enemy} plant was. Nur damit du es weißt.',
      'Ein Gast hat geredet. {enemy} will Ärger mit dir.',
    ],
    favor: [
      'Brauche Platz für ein paar Kisten übers Wochenende. {amount}.',
      'Goran. Kannst du was für uns bunkern? {amount}.',
      'Der Club ist zu heiß. Nimm unser Zeug, {amount}.',
      'Ein Gefallen, gut bezahlt: {amount} fürs Lagern.',
      'Wir brauchen deinen Keller bis Montag. {amount}.',
    ],
    warAsk: [
      'Die Tür geht auf {enemy} los, in {veedel}. Bist du dabei?',
      'Heute Nacht machen wir {enemy} den Laden dicht. Wer hilft, steht immer auf der Liste.',
      '{enemy} hat in {veedel} nichts verloren. Hilf uns, und du kommst überall rein.',
      'Goran fragt einmal: gegen {enemy}, mit Ware oder mit Leuten?',
      'Wir räumen {veedel} von {enemy}. Wer jetzt nicht mitmacht, bleibt draußen.',
    ],
  },
  // 🗝 Kotti-Familie, Tarek Haddad „der Onkel“: Familie, Respekt, ruhig, aber endgültig.
  'be-kotti': {
    warning: [
      'Bruder, in {veedel} wohnt die Familie. Da verkauft man nicht einfach so.',
      'Der Onkel lässt grüßen. {veedel} ist Familie. Du bist es nicht.',
      'Respekt ist alles. In {veedel} hast du ihn noch nicht gezeigt.',
      'Wir haben dich gesehen, in {veedel}. Die ganze Straße hat dich gesehen.',
      'In {veedel} kennt jeder jeden Cousin. Dich kennt keiner.',
    ],
    threat: [
      '{tribute} die Woche, dann bist du Gast in {veedel}. Gäste behandeln wir gut.',
      'Der Onkel sagt: {tribute} pro Woche. Für den Frieden in {veedel}.',
      'Jeder Späti zahlt. Du zahlst {tribute} die Woche, wie alle.',
      '{tribute} wöchentlich. Das ist Respekt in Zahlen.',
      'Für {veedel} sind es {tribute} die Woche. Der Onkel macht dir einen guten Preis.',
    ],
    war: [
      'Du hast die Familie beleidigt. Jetzt kommt die Familie.',
      'Der Onkel hat entschieden. Von heute an bist du Feind.',
      'Respekt verloren, alles verloren. Wir kommen.',
      'Kein Cousin wird dir mehr helfen. Keiner.',
      'Die ganze Familie weiß jetzt deinen Namen.',
    ],
    raidWon: [
      'Du hast dich gewehrt. Das zeigt Mut. Mut allein reicht nicht.',
      'Gut gekämpft, Bruder. Die Familie ist größer als du denkst.',
      'Heute du. Morgen wieder wir.',
      'Der Onkel hat zugeschaut. Er war fast beeindruckt.',
      'Eine Runde für dich. Die Familie hat Zeit.',
    ],
    raidLost: [
      'Das war eine Lektion. Der Onkel gibt sie nur einmal freundlich.',
      'Wir haben genommen, was der Familie zusteht.',
      'Die Cousins waren bei dir. Sie haben aufgeräumt.',
      'So sieht es aus, wenn man keinen Respekt zeigt.',
      'Deine Ware ist jetzt Familienbesitz.',
    ],
    attacked: [
      'Du hast einen Cousin angefasst. Das ist wie die Mutter anfassen.',
      'Der Onkel ist ruhig. Das ist das Schlimmste.',
      'Du greifst die Familie an? Hast du keine eigene?',
      'Für jeden von uns kommen zehn. Merk dir das.',
      'Das war unser Laden. Die Familie vergisst nicht.',
    ],
    snitch: [
      'Du redest mit der Polizei über die Familie? Bruder, das war ein Fehler.',
      'Ein Verräter. Der Onkel hat lange keinen mehr getroffen.',
      'Die Bullen hatten deinen Tipp. Wir haben deine Adresse.',
      'Wer petzt, verliert alles. Zuerst den Respekt.',
      'Die Familie hat Ohren auf jeder Wache. Wir wissen es.',
    ],
    tributeDue: [
      'Bruder, die Woche ist um. {tribute}.',
      'Der Onkel wartet auf {tribute}.',
      '{tribute}, wie immer. Ein Cousin holt es ab.',
      'Respekt zeigt man pünktlich: {tribute}.',
      'Zahltag für die Familie: {tribute}.',
    ],
    protectionRefused: [
      'Die Familie zahlt nicht an Fremde. Diese Woche nicht, nie.',
      'Der Onkel sagt: Wir schützen uns selbst.',
      'Kein Geld. Die Cousins reichen uns.',
      'Wir zahlen keinem. Komm und hol es, wenn du kannst.',
      'Abgelehnt. Respekt muss man sich verdienen, nicht kaufen.',
    ],
    offer: [
      'Ein Cousin hat {amount} übrig. {price}, Shisha-Bar in {veedel}.',
      'Der Onkel macht dir ein Angebot: {amount} für {price}. {veedel}.',
      'Familienpreis: {amount}, {price}. Abholen in {veedel}, heute.',
      'Aus dem Lager der Familie: {amount} für {price}. In {veedel}.',
      'Bruder, {amount} für {price}. Späti in {veedel}, frag nach Samir.',
    ],
    allianceOffer: [
      '{enemy} zeigt keinen Respekt. {price}, und du stehst bei der Familie.',
      'Der Onkel schlägt vor: zusammen gegen {enemy}. {price}.',
      'Die Familie braucht Freunde gegen {enemy}. Freundschaft kostet {price}.',
      'Mit uns gegen {enemy}, Bruder. {price}, und du gehörst fast dazu.',
      'Gemeinsam lehren wir {enemy} Respekt. Kostet {price}.',
    ],
    intimidation: [
      'Am {spot} stehen jetzt drei Cousins. Deine Kunden gehen lieber woanders hin.',
      'Der Onkel hat Leute an deinen {spot} geschickt. Nur zum Reden.',
      'Am {spot} sitzt jetzt die Familie. Ganz gemütlich.',
      'Deine Kunden am {spot} haben eine neue Adresse bekommen. Unsere.',
      'Der {spot} ist heute Familientreffen.',
    ],
    tipOff: [
      'Ein Cousin arbeitet beim Ordnungsamt. {veedel} wird bald kontrolliert.',
      'Der Onkel hat telefoniert. Die Polizei interessiert sich für {veedel}.',
      'In {veedel} gibt es bald mehr Blaulicht. Respekt kostet.',
      'Die Bullen haben einen Hinweis zu {veedel}. Von wem, fragst du?',
      'Ein Wort an den richtigen Mann, und {veedel} wird heiß.',
    ],
    blackmail: [
      'Wir wissen, wo dein {warehouse} ist. {amount}, und die Familie schweigt.',
      'Der Onkel. {amount}, sonst erfährt die Polizei vom {warehouse}.',
      'Dein {warehouse} liegt in unserer Straße. {amount} Miete für das Schweigen.',
      '{amount}, und der {warehouse} bleibt in der Familie.',
      'Für {amount} hat kein Cousin den {warehouse} je gesehen.',
    ],
    warnRival: [
      'Bruder, ein Rat von der Familie: {enemy} will dir schaden.',
      'Der Onkel hat gehört: {enemy} kommt zu dir.',
      'Ein Cousin sagt, {enemy} sammelt Leute gegen dich.',
      '{enemy} redet schlecht über dich. Das ist nie gut.',
      'Pass auf, Bruder. {enemy} plant etwas.',
    ],
    favor: [
      'Die Familie braucht Platz für Ware. {amount}, drei Tage.',
      'Der Onkel bittet um einen Gefallen: Lager für uns, {amount}.',
      'Unsere Keller sind zu bekannt. Nimm unsere Kisten, {amount}.',
      'Ein Gefallen unter Freunden, bezahlt: {amount}.',
      'Bruder, kannst du was verstecken? {amount}.',
    ],
    warAsk: [
      'Die Familie geht gegen {enemy} in {veedel}. Stehst du bei uns?',
      'Der Onkel fragt dich: Hilfst du gegen {enemy}? Er merkt sich die Antwort.',
      '{enemy} will {veedel}. Hilf der Familie, und die Familie hilft dir.',
      'Gegen {enemy}, Bruder. Leute oder Ware, Hauptsache du bist dabei.',
      'Heute zeigen wir {enemy}, wem {veedel} gehört. Bist du Freund oder nicht?',
    ],
  },
  // 🐺 Leo-Gang, Kevin „Kralle“ Schulz: Berliner Schnauze, rotzig, laut.
  'be-leo': {
    warning: [
      'Ey, Alter. {veedel} is unser Kiez, wa. Verpiss dich.',
      'Kralle hier. Du in {veedel}? Echt jetzt? Na warte.',
      'In {veedel} verkaufen wir. Du nich. Kapiert?',
      'Haste dich verlaufen? {veedel} is nich dein Spielplatz.',
      'Letzte Ansage, Digga: Raus aus {veedel}.',
    ],
    threat: [
      '{tribute} die Woche, sonst gibt’s auf die Fresse. In {veedel}, wa.',
      'Kralle will {tribute} pro Woche. Is billig, ehrlich.',
      'Zahlste {tribute} die Woche, kannste in {veedel} bleiben. Zahlste nich, biste weg.',
      'Alter, {tribute} wöchentlich. Sonst kommen wir vorbei.',
      '{tribute} jede Woche für {veedel}. Und keene Diskussion.',
    ],
    war: [
      'Jetzt isses vorbei, Alter. Wir kommen.',
      'Kralle hat die Schnauze voll. Pass auf deine Ecken auf.',
      'Ab jetzt gibt’s Stress. Jeden Tag.',
      'Du hast es verkackt. Der Leo kommt.',
      'Krieg, Digga. Und wir sind mehr.',
    ],
    raidWon: [
      'Glück gehabt, du Lauch. Nächstes Mal nich.',
      'Okay, okay. Haste Eier. Wir kommen trotzdem wieder.',
      'Meine Jungs sind am Arsch. Morgen sind se wieder fit.',
      'Einmal gewonnen is nich immer gewonnen, Alter.',
      'Krass. Aber der Leo vergisst nix.',
    ],
    raidLost: [
      'Haha. Abgezogen, Alter.',
      'Deine Ware is jetzt unsere. Danke, wa.',
      'Das war der Leo. Grüße an deine Leute.',
      'Zack, weg. So läuft das bei uns.',
      'Na, wie fühlt sich das an? Schön leer?',
    ],
    attacked: [
      'Du gehst auf uns? Bist du bescheuert?',
      'Kralle is sauer. Richtig sauer.',
      'Das war unsere Ecke, du Opfer. Jetzt brennt’s.',
      'Keener haut den Leo. Keener.',
      'Na warte. Wir sind gleich da.',
    ],
    snitch: [
      'Du hast uns verpfiffen? Bei den Bullen? Alter.',
      'Petze. Weißt du, was wir mit Petzen machen?',
      'Die Bullen wussten Bescheid. Wir wissen, von wem.',
      'Ratte. Echt jetzt.',
      'Kralle hat deinen Namen gehört. Von der Wache. Das war dumm.',
    ],
    tributeDue: [
      'Kohle, Alter. {tribute}.',
      'Woche rum. {tribute}, aber zackig.',
      'Kralle will {tribute}. Jetze.',
      '{tribute}, wie immer. Nich vergessen, wa.',
      'Zahltag, Digga: {tribute}.',
    ],
    protectionRefused: [
      'Zahlen? Wir? An dich? Haha.',
      'Nix gibt’s, Alter.',
      'Kralle sagt: Leck mich.',
      'Wir brauchen keenen Schutz. Wir sind der Ärger.',
      'Kohle gibt’s keene. Hol se dir doch.',
    ],
    offer: [
      'Alter, ich hab {amount} rumliegen. {price}, am Leo in {veedel}.',
      'Kralle verkauft: {amount} für {price}. {veedel}, schnell.',
      'Billig, billig: {amount} für {price}. {veedel}, heute noch.',
      'Is nich die beste Ware, aber billig: {amount}, {price}. {veedel}.',
      'Digga, {amount} für {price}. Komm nach {veedel}.',
    ],
    allianceOffer: [
      '{enemy} nervt. {price} und wir hauen die zusammen weg.',
      'Kralle sagt: du und wir gegen {enemy}. {price}.',
      'Gegen {enemy} brauchen wir Leute. Haste welche? {price}.',
      'Zusammen gegen {enemy}, Alter. Für {price}.',
      '{enemy} muss weg. {price}, dann sind wir Kumpels.',
    ],
    intimidation: [
      'Wir hängen jetzt an deinem {spot} ab. Viel Spaß mit deinen Kunden.',
      'Kralle und die Jungs chillen am {spot}. Deine Kunden haben Angst.',
      'Am {spot} gibt’s jetzt Ärger. Unseren.',
      'Der {spot} is jetzt Leo-Gebiet. Pech.',
      'Wir sitzen auf deinem {spot}. Und wir gehen nich.',
    ],
    tipOff: [
      'Hab den Bullen was über {veedel} gesteckt. Haha.',
      'Kralle hat die 110 gewählt. Wegen {veedel}.',
      'In {veedel} gibt’s bald Blaulicht, Alter.',
      'Die Bullen wissen jetzt, was du in {veedel} machst.',
      'Ups. Wir haben über {veedel} gequatscht.',
    ],
    blackmail: [
      'Wir wissen, wo dein {warehouse} is. {amount}, sonst wissen’s die Bullen auch.',
      'Kralle. {amount} oder wir knacken den {warehouse}.',
      'Geiles Lager, der {warehouse}. {amount}, dann bleibt’s geil.',
      '{amount}, und wir vergessen den {warehouse}.',
      'Alter, {amount}. Sonst is der {warehouse} morgen leer.',
    ],
    warnRival: [
      'Ey, {enemy} will dich abziehen. Nur so.',
      'Kralle sagt: Pass auf {enemy} auf.',
      'Hab gehört, {enemy} kommt zu dir. Viel Glück, Alter.',
      '{enemy} will Stress mit dir. Haha.',
      'Digga, {enemy} sammelt Leute.',
    ],
    favor: [
      'Ey, kannste was für uns lagern? {amount}.',
      'Kralle braucht ’nen Keller. {amount}.',
      'Unser Zeug muss weg von der Straße. {amount}, drei Tage.',
      'Gefallen gegen Kohle: {amount}.',
      'Alter, nimm unsere Kisten. {amount}.',
    ],
    warAsk: [
      'Wir gehen auf {enemy} los, in {veedel}. Biste dabei, Alter?',
      'Kralle fragt: Hilfste gegen {enemy}? Ja oder nee?',
      '{enemy} hat in {veedel} nix zu suchen. Hilf uns, Digga.',
      'Gegen {enemy}! Leute, Ware, egal, Hauptsache du machst mit.',
      'Heute gibt’s auf die Fresse für {enemy}. Kommste mit?',
    ],
  },
  // 🥂 Kudamm-Kreis, Konstantin von Arnim: höflich, gebildet, kalt.
  'be-westend': {
    warning: [
      'Guten Abend. Ich muss Sie bitten, {veedel} unseren Kunden zu überlassen.',
      'Von Arnim. Ihre Anwesenheit in {veedel} ist uns aufgefallen. Unangenehm aufgefallen.',
      'In {veedel} pflegen wir einen gewissen Stil. Ihrer passt nicht.',
      'Ein freundlicher Hinweis: Die Kundschaft in {veedel} ist vergeben.',
      'Man hat mir berichtet, Sie seien in {veedel} tätig. Ich empfehle, das zu überdenken.',
    ],
    threat: [
      'Für {veedel} halten wir {tribute} pro Woche für angemessen.',
      'Von Arnim. {tribute} wöchentlich, und wir sehen über {veedel} hinweg.',
      'Unsere Konditionen: {tribute} je Woche. Diskret, wie alles bei uns.',
      'Ein kleiner Beitrag von {tribute} die Woche sichert Ihnen Ruhe in {veedel}.',
      '{tribute} pro Woche. Betrachten Sie es als Mitgliedsbeitrag.',
    ],
    war: [
      'Sie lassen mir keine Wahl. Ab sofort betrachten wir Sie als Problem.',
      'Von Arnim. Das Gespräch ist beendet. Andere übernehmen jetzt.',
      'Ich bedaure. Wirklich. Aber wir müssen Sie entfernen.',
      'Unsere Anwälte haben Feierabend. Unsere anderen Leute nicht.',
      'Sie haben den Kreis verärgert. Das war unklug.',
    ],
    raidWon: [
      'Bemerkenswert. Wir werden unsere Mittel anpassen.',
      'Sie haben sich behauptet. Vorerst.',
      'Ein Achtungserfolg, zugegeben. Der Kudamm hat einen langen Atem.',
      'Von Arnim gratuliert. Und plant.',
      'Interessant. Wir lernen dazu, Sie hoffentlich auch.',
    ],
    raidLost: [
      'Ich hoffe, Sie verstehen die Botschaft. Sie war teuer genug.',
      'Der Kreis hat sich genommen, was ihm zusteht. Zuzüglich Spesen.',
      'Eine bedauerliche Begegnung. Für Sie.',
      'Ihre Ware befindet sich nun in besseren Händen.',
      'So regeln wir das am Kudamm. Gründlich.',
    ],
    attacked: [
      'Sie haben unsere Leute angegriffen. Das wird Folgen haben, juristische und andere.',
      'Von Arnim ist enttäuscht. Und Enttäuschung hat bei uns einen Preis.',
      'Ein Angriff auf den Kreis. Wie unzivilisiert.',
      'Sie werden das bereuen. Ich sorge persönlich dafür.',
      'Gewalt ist so gewöhnlich. Aber wenn Sie darauf bestehen.',
    ],
    snitch: [
      'Sie haben mit der Polizei gesprochen. Wir auch, und wir kennen die Leute länger.',
      'Ein Hinweis an die Behörden. Ausgerechnet von Ihnen. Wie geschmacklos.',
      'Unser Anwalt hat die Akte gelesen. Ihr Name steht darin.',
      'Denunziation ist ein schmutziges Geschäft. Sie werden es merken.',
      'Von Arnim weiß, wer geplaudert hat. Er schätzt das nicht.',
    ],
    tributeDue: [
      'Die Woche ist um. {tribute}, bitte.',
      'Von Arnim erinnert an {tribute}.',
      'Ihr Beitrag: {tribute}. Wie vereinbart.',
      '{tribute} sind fällig. Wir schätzen Pünktlichkeit.',
      'Mit freundlichen Grüßen: {tribute}.',
    ],
    protectionRefused: [
      'Wir zahlen nicht. Wir lassen zahlen.',
      'Von Arnim lehnt ab. Höflich, aber bestimmt.',
      'Schutz kaufen wir bei Anwälten, nicht bei Ihnen.',
      'Diese Woche keine Zahlung. Auch keine nächste.',
      'Ein Missverständnis. Der Kreis zahlt grundsätzlich nicht.',
    ],
    offer: [
      'Wir hätten {amount} feinster Qualität abzugeben. {price}. Diskrete Übergabe in {veedel}.',
      'Von Arnim. {amount} für {price}. Hotelbar in {veedel}.',
      'Ein exklusives Angebot: {amount}, {price}. In {veedel}, nur heute.',
      'Aus dem Bestand des Kreises: {amount} zu {price}. {veedel}.',
      '{amount} für {price}. Abholung in {veedel}, bitte unauffällig.',
    ],
    allianceOffer: [
      '{enemy} wird lästig. Für {price} stünden wir an Ihrer Seite.',
      'Von Arnim schlägt eine Zusammenarbeit gegen {enemy} vor. Honorar: {price}.',
      'Gegen {enemy} wären wir gemeinsam stärker. {price}, und wir sind uns einig.',
      'Ein Bündnis gegen {enemy}. Unsere Gebühr: {price}.',
      'Für {price} lösen wir das Problem {enemy} gemeinsam.',
    ],
    intimidation: [
      'Vor Ihrem {spot} parkt jetzt ein Wagen von uns. Ihre Kunden fühlen sich beobachtet.',
      'Von Arnim hat Personal an Ihren {spot} geschickt. Rein zur Beobachtung.',
      'Am {spot} sind jetzt unsere Leute. Sehr höflich, sehr präsent.',
      'Ihr {spot} wird ab sofort von uns betreut.',
      'Ihre Kundschaft am {spot} wurde gebeten, woanders einzukaufen.',
    ],
    tipOff: [
      'Ein befreundeter Staatsanwalt interessiert sich nun für {veedel}.',
      'Von Arnim hat beim Abendessen {veedel} erwähnt. Vor den falschen Leuten.',
      'Die Behörden erhielten einen Hinweis zu {veedel}. Anonym, selbstverständlich.',
      'In {veedel} wird man bald genauer hinsehen. Wir haben darum gebeten.',
      'Ein Anruf genügte. {veedel} steht nun auf einer Liste.',
    ],
    blackmail: [
      'Uns ist die Adresse Ihres {warehouse} bekannt. {amount} wären ein fairer Preis für Diskretion.',
      'Von Arnim. {amount}, oder die Behörden erfahren vom {warehouse}.',
      'Der {warehouse}, eine interessante Immobilie. {amount}, und sie bleibt Ihre.',
      'Für {amount} vergessen wir den {warehouse}. Schriftlich, wenn Sie möchten.',
      '{amount}. Dann bleibt der {warehouse} ein Geheimnis unter Gentlemen.',
    ],
    warnRival: [
      'Eine Warnung, unverbindlich: {enemy} plant etwas gegen Sie.',
      'Von Arnim lässt ausrichten: {enemy} sammelt Leute.',
      'Man hört, {enemy} interessiert sich für Sie. Nicht freundlich.',
      'Seien Sie vorsichtig. {enemy} ist unruhig.',
      'Unter uns: {enemy} wird Ihnen bald einen Besuch abstatten.',
    ],
    favor: [
      'Wir bräuchten diskrete Lagerfläche für einige Tage. {amount}.',
      'Von Arnim bittet um einen Gefallen: Lager, {amount}.',
      'Unsere Villa ist derzeit ungeeignet. Würden Sie etwas verwahren? {amount}.',
      'Ein kleiner Dienst, angemessen vergütet: {amount}.',
      'Für {amount} nähmen Sie uns einige Kisten ab?',
    ],
    warAsk: [
      'Der Kreis geht gegen {enemy} in {veedel} vor. Dürfen wir auf Sie zählen?',
      'Von Arnim fragt höflich: Unterstützen Sie uns gegen {enemy}?',
      '{enemy} hat in {veedel} nichts verloren. Ihre Hilfe würde nicht vergessen.',
      'Gegen {enemy}: Leute oder Ware, Sie entscheiden. Wir merken es uns.',
      'Heute räumen wir {veedel} von {enemy}. Wir erwarten Ihre Entscheidung.',
    ],
  },
};
