// Stimmen der Münchner Gangs (Auftrag 38), nach dem Muster von texts.ts: je Anlass mindestens fünf eigene Varianten.
// Ton: Goldene Hand geschäftsmäßig mit Fahrplan im Kopf (der Schaffner), Giasinga Buam derb bairisch, Isar-Konsortium
// Grüß-Gott-Höflichkeit mit Freunden im Präsidium, Nordblock Hochhaus-Ton aus dem Norden.

import type { GangVoice } from './texts';

export const GANG_VOICES_MUENCHEN: Readonly<Record<string, GangVoice>> = {
  // ✋ Goldene Hand, Dragan Kovač „der Schaffner“: kurz, geschäftsmäßig, Bahnhof und Fahrplan.
  'mu-bahnhof': {
    warning: [
      'Fahrkartenkontrolle. In {veedel} fährt keiner ohne Ticket von uns. Du hast keins.',
      'Der Schaffner hat dich in {veedel} gesehen. Nächster Halt: Ärger.',
      '{veedel} ist unser Bahnsteig. Wer hier verkauft, steigt bei uns ein oder bleibt draußen.',
      'Freundliche Durchsage: Verkauf in {veedel} nur mit Genehmigung der Goldenen Hand.',
      'Dragan hier. In {veedel} läuft alles nach Fahrplan. Du stehst nicht drauf.',
    ],
    threat: [
      'Das Ticket für {veedel} kostet {tribute} die Woche. Ohne Ticket wirst du rausgesetzt.',
      'Wochenkarte: {tribute}. Dann fährst du in {veedel} mit, ohne Kontrolle.',
      '{tribute} pro Woche, pünktlich wie die S-Bahn. Also pünktlicher.',
      'Der Schaffner will {tribute} die Woche. Sonst endet deine Fahrt in {veedel}.',
      'Schwarzfahren ist teuer. {tribute} wöchentlich ist billiger.',
    ],
    war: [
      'Endstation. Ab heute fährt kein Zug mehr für dich.',
      'Du bist aus dem Fahrplan gestrichen. Meine Leute warten an jedem Gleis.',
      'Letzte Durchsage für dich: Bitte nicht mehr einsteigen.',
      'Die Goldene Hand macht die Faust. Gute Reise.',
      'Ab jetzt kontrolliere ich nicht mehr. Ab jetzt räume ich ab.',
    ],
    raidWon: [
      'Verspätung im Betriebsablauf. Der nächste Zug kommt bestimmt.',
      'Heute bist du durchgekommen. Der Schaffner merkt sich Gesichter.',
      'Glück gehabt. Das nächste Mal steigen mehr von uns zu.',
      'Ein Ausfall. Kommt vor. Nicht oft.',
      'Notiert unter Störungen. Wird behoben.',
    ],
    raidLost: [
      'Fahrgeld kassiert. Mit Zuschlag.',
      'Das war die Kontrolle. Deine Ware fährt jetzt mit uns.',
      'Ausgestiegen, und zwar unfreiwillig. So läuft das am Bahnhof.',
      'Die Goldene Hand nimmt, was rumliegt. Heute lag viel rum.',
      'Strafe für Schwarzfahren: alles. Danke.',
    ],
    attacked: [
      'Du hast einen von uns vom Bahnsteig geschubst. Jetzt kommt der ganze Zug.',
      'Der Schaffner ist nicht mehr freundlich. Das war dein Fehler.',
      'Angriff auf die Goldene Hand. Das wird teuer, und zwar für dich.',
      'Du hast meine Leute angefasst. Ich fasse jetzt deine an.',
      'Störung im Betrieb. Wir beheben das. Bei dir.',
    ],
    snitch: [
      'Die Bundespolizei am Bahnhof wusste plötzlich alles. Von dir, sagen sie.',
      'Du hast gequatscht. Am Bahnhof hört man alles, auch das.',
      'Ein Petzer im Fahrplan. Den streichen wir.',
      'Dein Name stand im Protokoll. Jetzt steht er bei uns auf der Liste.',
      'Verpfeifen ist am Bahnhof das Letzte, was man macht. Wörtlich.',
    ],
    tributeDue: [
      'Wochenkarte läuft ab: {tribute}.',
      'Der Schaffner kommt kassieren. {tribute}.',
      'Dragan. {tribute} sind fällig, wie jeden Montag.',
      '{tribute}, bar, am Schließfach wie immer.',
      'Fahrgeld bitte: {tribute}.',
    ],
    protectionRefused: [
      'Die Goldene Hand zahlt nicht. Wir sind der Fahrplan.',
      'Kein Geld diese Woche. Der Schaffner sagt Nein.',
      'Abgelehnt. Am Bahnhof zahlen die anderen.',
      'Wir zahlen kein Ticket. Wir verkaufen sie.',
      'Nichts da. Hol es dir am Gleis, wenn du dich traust.',
    ],
    offer: [
      'Aus dem Schließfach: {amount} für {price}. Abholen in {veedel}.',
      'Dragan. {amount}, {price}, {veedel}. Der Zug wartet nicht ewig.',
      'Übrig vom Wochenende: {amount}. {price}, Treffpunkt {veedel}.',
      'Sonderangebot am Bahnsteig: {amount} für {price}. Nur heute, {veedel}.',
      'Ein Koffer zu viel: {amount}. {price}. Frag in {veedel} nach dem Schaffner.',
    ],
    allianceOffer: [
      '{enemy} stört unseren Betrieb. {price}, und wir fahren zusammen.',
      'Der Schaffner bietet eine Partnerschaft gegen {enemy}. Kostet {price}.',
      'Gemeinsam gegen {enemy}: {price}, und du bekommst ein Gleis.',
      'Wir brauchen Leute gegen {enemy}. Du hast welche. {price}.',
      'Bündnis auf Zeit gegen {enemy}. Fahrpreis: {price}.',
    ],
    intimidation: [
      '{AtSpot} stehen jetzt meine Kontrolleure. Deine Kunden haben kein Ticket.',
      '{AtSpot} ist ab heute Sperrgebiet. Sagt die Goldene Hand.',
      'Fahrkartenkontrolle {atSpot}. Für deine Kunden heißt das: aussteigen.',
      'Meine Leute warten {atSpot}. Nicht auf den Bus.',
      '{AtSpot} hält heute keiner bei dir. Wir stehen im Weg.',
    ],
    tipOff: [
      'Die Bundespolizei hat einen Tipp zu {veedel} bekommen. Nicht von mir. Natürlich.',
      'Dragan hat telefoniert. In {veedel} wird es gleich voll mit Uniformen.',
      'Durchsage an die Polizei: In {veedel} lohnt sich ein Blick.',
      'Ein Wort am Bahnhof, und {veedel} wird kontrolliert.',
      'Ich hab die Streife nach {veedel} geschickt. Gute Fahrt.',
    ],
    blackmail: [
      'Ich weiß, wo dein {warehouse} ist. {amount}, und ich vergesse den Weg.',
      'Dragan. {amount}, oder die Polizei bekommt die Adresse vom {warehouse}.',
      'Dein {warehouse} steht in meinem Fahrplan. {amount}, und ich streiche ihn.',
      '{amount}, dann bleibt der {warehouse} ein Geheimnis.',
      'Für {amount} habe ich den {warehouse} nie gesehen.',
    ],
    warnRival: [
      'Durchsage: {enemy} plant was gegen dich.',
      'Der Schaffner hört viel. {enemy} sammelt Leute.',
      'Kleiner Hinweis vom Bahnsteig: {enemy} kommt.',
      'Pass auf. {enemy} ist unterwegs zu dir.',
      'Gratis-Tipp: {enemy} will dich aus dem Verkehr ziehen.',
    ],
    favor: [
      'Ich brauche ein Schließfach. Deinen Keller. {amount}.',
      'Dragan. Kannst du drei Tage was lagern? {amount}.',
      'Der Bahnhof ist zu heiß. Nimm unsere Koffer, {amount}.',
      'Ein bezahlter Gefallen: {amount} fürs Aufbewahren.',
      'Gepäckaufbewahrung bei dir: {amount}.',
    ],
    warAsk: [
      'Wir räumen {enemy} aus {veedel}. Steigst du ein?',
      'Die Goldene Hand geht gegen {enemy}. Wer hilft, fährt danach umsonst.',
      '{enemy} hat in {veedel} nichts verloren. Hilf uns, es wird sich lohnen.',
      'Einmal frage ich: {enemy}, {veedel}, du und wir. Ja oder nein?',
      'Abfahrt gegen {enemy}. Wer jetzt nicht einsteigt, bleibt stehen.',
    ],
  },
  // 🦁 Giasinga Buam, Xaver „Wasti“ Huber: derb, bairisch, stolz auf Giesing.
  'mu-giesing': {
    warning: [
      'Servus, Saupreiß. {veedel} is unser Viertel. Schleich di.',
      'Da Wasti hod di gseng. In {veedel}. Des war des letzte Moi.',
      'Hörst, Bua. In {veedel} verkafft nur oana, und des bist ned du.',
      'Mia ham di in {veedel} gseng. Oamoi sag i des, oamoi.',
      'Pack dei Glump zam und geh hoam. {veedel} ghört de Buam.',
    ],
    threat: [
      '{tribute} de Woch, sonst kemma vorbei. In {veedel}. Mit oi de Buam.',
      'Da Wasti mog {tribute} pro Woch. Is billiger wia a neis Gebiss.',
      '{tribute} jede Woch, bar auf d’Hand, dann derfst in {veedel} weida.',
      'Letzte Ansag: {tribute} de Woch. Oda es kracht.',
      'Meine Buam san scho narrisch. {tribute} beruhigt de. Du host de Wahl.',
    ],
    war: [
      'Guad. Dann hoid so. Ab heit schaugst di besser um.',
      'Du wuist an Krieg? Kriagst oan. Giesing vergisst nix.',
      'Ab heit bist a Gejagter. Grüß dei Leid, solang’s no stehn.',
      'Jetzt redn ned mehr mia. Jetzt redn d’Fäust.',
      'Aus is und gar is. Pass auf, wo’d hinlangst.',
    ],
    raidWon: [
      'Heit host Glück ghabt. Des hoit ned ewig.',
      'Respekt, Bua. Aber mia san no ned fertig.',
      'Oamoi is koamoi. Mia kemma wieder.',
      'Meine Buam san angschlogn. Des merkn ma uns.',
      'Des war a Unentschieden. Des Rückspiel kimmt.',
    ],
    raidLost: [
      'Des war a Watschn, und a gscheide.',
      'Dei Zeig ghört jetzt uns. Vergelt’s Gott.',
      'So schaugt’s aus in Giesing. Merk da des.',
      'Abgräumt. Wia nach am Heimsieg.',
      'Mia ham dei Ware. Du host a blaus Aug. Passt scho.',
    ],
    attacked: [
      'Du host oan vo de Buam umglegt. Jetzt kemma alle.',
      'Da Wasti is grantig. Und wenn da Wasti grantig is, werd’s laut.',
      'Des war a Fehler, Saupreiß. A großer.',
      'In Giesing schlogt koana ungstraft zua.',
      'Du host gegen Giesing glangt. Des werst bereun.',
    ],
    snitch: [
      'Du host d’Polizei gschickt? Mia ham an Ratschkathl gfundn.',
      'A Verräter. In Giesing gibt’s nix Schlimmers.',
      'Mia wissen, wer gratscht hod. Du.',
      'D’Streife war do. Dei Nam stand auf eanam Zettl. Jetzt aa auf unserm.',
      'Verpfiffn. Des vergisst a Giesinger ned, nia ned.',
    ],
    tributeDue: [
      'Zahltag, Bua: {tribute}.',
      'Da Wasti kassiert. {tribute}.',
      '{tribute} san fällig. Bar, im Wettbüro.',
      'Neie Woch, {tribute}. Wia oiwei.',
      'Her mit de {tribute}. Und zwar glei.',
    ],
    protectionRefused: [
      'Mia zoin nix. Mia san de Buam.',
      'Schutzgeld? Mia san da Schutz.',
      'Nix gibt’s. Hoi’s da, wennst di traust.',
      'Abglehnt. In Giesing zoit ma ned.',
      'Diese Woch zoin mia ned. Und nächste aa ned.',
    ],
    offer: [
      'Mia ham {amount} übrig. {price}, abhoin in {veedel}.',
      'Wasti. {amount} für {price}. Hinterm Wettbüro in {veedel}.',
      'A Sonderangebot vom Sechzger: {amount}, {price}, {veedel}.',
      '{amount} san übrig. {price}. Kimm noch {veedel}, aber alloa.',
      'Heit gibt’s {amount} für {price}. Nur heit, in {veedel}.',
    ],
    allianceOffer: [
      '{enemy} geht uns aufn Senkel. {price}, und du bist dabei.',
      'Mia und du gegen {enemy}. Kost di {price}.',
      'Da Wasti bietet: zam gegen {enemy}. {price}.',
      'Mia brauchan Leid gegen {enemy}. {price}, dann san ma Spezln.',
      'Giesing gegen {enemy}. Eintritt für di: {price}.',
    ],
    intimidation: [
      'Meine Buam stehn jetzt {atSpot}. Wer vorbei mog, muass zahln.',
      '{AtSpot} is jetzt Heimspiel. Für uns.',
      '{AtSpot} san heit de Buam. Dei Kundschaft traut si ned hi.',
      'Fünf vo uns {atSpot}. Viel Spaß beim Verkaffa.',
      '{AtSpot} gibt’s heit nix für di. Sagt da Wasti.',
    ],
    tipOff: [
      'D’Polizei woas jetzt, was in {veedel} lafft. Griaß di.',
      'Da Wasti hod telefoniert. {veedel} werd hoaß.',
      'A Wort beim Wirt, und a Bulle hört zua. {veedel}, mei Liaba.',
      'Mia ham da Streife a Tipp gebn. Zu {veedel}.',
      'In {veedel} werd’s glei blau. Ned vom Himme.',
    ],
    blackmail: [
      'I woaß, wo dei {warehouse} is. {amount}, sonst woaß es d’Polizei aa.',
      'Wasti. {amount} oda d’Bullen kriagn dein {warehouse}.',
      'Dei {warehouse} is schee glegn. {amount}, dann vergiss i d’Hausnummer.',
      '{amount}, dann bleibt da {warehouse} unter uns.',
      'Für {amount} hob i nia wos vom {warehouse} ghört.',
    ],
    warnRival: [
      'A Tipp vo de Buam: {enemy} mog an di hi.',
      'Pass auf, {enemy} plant wos.',
      'Hob beim Wirt ghört: {enemy} kimmt zu dir.',
      '{enemy} sammelt Leid. Gegen di.',
      'Unter Nachbarn: {enemy} suacht Stress.',
    ],
    favor: [
      'Mia bräuchtn an Keller für a paar Kistn. {amount}.',
      'Wasti. Konnst wos für uns lagern? {amount}.',
      'In Giesing is grad z’hoaß. Nimm unser Zeig, kriagst {amount}.',
      'A Gfoin, zoit: {amount} fürs Bunkern.',
      'Drei Dog Lagern. {amount}.',
    ],
    warAsk: [
      'Mia gehn auf {enemy} los, in {veedel}. Bist dabei?',
      'Heit Nacht räuma mia bei {enemy} auf. Wer hilft, is a Spezl.',
      '{enemy} hod in {veedel} nix verlorn. Hilf uns, dann host in Giesing Kredit.',
      'I frag oamoi: Gegen {enemy}, bist dabei?',
      'De Buam ziehn gegen {enemy}. Wer jetzt kneift, is draußen.',
    ],
  },
  // 💎 Isar-Konsortium, Dr. Benedikt von Arnim: Grüß Gott, Golfplatz, Freunde im Präsidium.
  'mu-isar': {
    warning: [
      'Grüß Gott. Man hat Sie in {veedel} gesehen. Das war kein guter Eindruck.',
      'Dr. von Arnim lässt ausrichten: {veedel} ist vergeben. Seit Jahren.',
      'In {veedel} verkehren Sie nicht. Das ist keine Bitte.',
      'Ein Hinweis unter Geschäftsleuten: {veedel} gehört dem Konsortium.',
      'Wir möchten Sie in {veedel} nicht noch einmal antreffen. Grüß Gott.',
    ],
    threat: [
      'Das Konsortium erhebt eine Gebühr: {tribute} wöchentlich für {veedel}.',
      '{tribute} pro Woche. Dafür bleibt {veedel} ruhig, auch für Sie.',
      'Dr. von Arnim schlägt {tribute} pro Woche vor. Ein Freundschaftspreis.',
      'Eine Beteiligung von {tribute} die Woche. Sonst wird es ungemütlich in {veedel}.',
      'Für {tribute} wöchentlich spricht niemand im Präsidium über Sie.',
    ],
    war: [
      'Das Konsortium hat entschieden. Sie sind ab heute unerwünscht, in ganz München.',
      'Der Doktor hat telefoniert. Mit Leuten, die Sie nicht kennenlernen möchten.',
      'Grüß Gott, und auf Nimmerwiedersehen.',
      'Wir beenden die Geduld. Was folgt, wird unangenehm.',
      'Sie haben es so gewollt. Wir haben Anwälte, Freunde und Zeit.',
    ],
    raidWon: [
      'Ein Ergebnis, das wir nicht erwartet hatten. Es wird korrigiert.',
      'Gut gespielt. Auf dem Golfplatz verliert man auch mal ein Loch.',
      'Bemerkenswert. Wir haben es notiert.',
      'Sie hatten Glück. Wir haben Geduld.',
      'Der Doktor lässt gratulieren. Ironisch.',
    ],
    raidLost: [
      'Das Konsortium hat seine Ansprüche durchgesetzt.',
      'Ihre Ware befindet sich jetzt in besseren Händen.',
      'Eine Lektion, gratis. Die nächste kostet.',
      'Grüß Gott. Und danke für die Ware.',
      'So regelt man das an der Isar.',
    ],
    attacked: [
      'Sie haben Leute des Konsortiums angegriffen. Das hat Konsequenzen, auch juristische.',
      'Der Doktor ist enttäuscht. Enttäuschung ist teurer als Wut.',
      'Ein Übergriff. Wir haben Zeugen, Anwälte und Freunde.',
      'Sie haben die Isar aufgewühlt. Sie wird Sie mitnehmen.',
      'Unsere Leute bluten selten. Ihre werden es öfter tun.',
    ],
    snitch: [
      'Sie haben die Polizei auf uns angesetzt? Der Polizeipräsident spielt mit uns Golf.',
      'Ein Hinweis an die Kripo. Von Ihnen. Wir lesen die Akten mit.',
      'Verrat ist im Konsortium ein Kündigungsgrund. Für alles.',
      'Wir wissen, wer angerufen hat. Wir wissen immer, wer anruft.',
      'Sie haben gesprochen. Jetzt sprechen wir. Über Sie.',
    ],
    tributeDue: [
      'Die Gebühr ist fällig: {tribute}.',
      'Dr. von Arnim erinnert an {tribute}.',
      '{tribute}, wie vereinbart. Diskret, bitte.',
      'Die Wochenrechnung des Konsortiums: {tribute}.',
      'Grüß Gott. {tribute} sind zu überweisen. Bar.',
    ],
    protectionRefused: [
      'Das Konsortium zahlt keine Gebühren. Es erhebt sie.',
      'Abgelehnt. Wir sind nicht diejenigen, die zahlen.',
      'Der Doktor lehnt höflich ab.',
      'Schutz? Wir haben Anwälte.',
      'Keine Zahlung. Grüß Gott.',
    ],
    offer: [
      'Eine Partie bester Ware: {amount} für {price}. Abholung in {veedel}.',
      'Das Konsortium veräußert {amount}. {price}. Diskret, in {veedel}.',
      'Feine Ware, {amount}, {price}. Ein Fahrer wartet in {veedel}.',
      'Nur für ausgewählte Partner: {amount} zu {price}, {veedel}.',
      'Restbestand aus dem Club: {amount}, {price}. In {veedel}.',
    ],
    allianceOffer: [
      '{enemy} wird lästig. Ein Bündnis kostet Sie {price}.',
      'Das Konsortium sucht Partner gegen {enemy}. Einlage: {price}.',
      'Gemeinsam gegen {enemy}. Ihr Beitrag: {price}.',
      'Dr. von Arnim schlägt eine Allianz gegen {enemy} vor. {price}.',
      'Gegen {enemy} brauchen wir Hände. Sie haben welche. {price}.',
    ],
    intimidation: [
      '{AtSpot} stehen jetzt Herren in guten Anzügen. Ihre Kundschaft versteht.',
      '{AtSpot} betreut ab heute das Konsortium.',
      '{AtSpot} parkt ein schwarzer Wagen. Ihre Kunden fahren weiter.',
      'Grüß Gott {atSpot}. Für Ihre Kunden heißt das: auf Wiedersehen.',
      'Unsere Leute sind {atSpot}. Höflich und unübersehbar.',
    ],
    tipOff: [
      'Ein Bekannter im Präsidium interessiert sich jetzt für {veedel}.',
      'Der Doktor hat beim Abendessen von {veedel} erzählt. Einem Kriminalrat.',
      'In {veedel} wird bald gründlich geprüft. Wir haben es angeregt.',
      'Ein diskreter Hinweis zu {veedel} ist eingegangen. Von uns.',
      'Die Polizei hat jetzt einen Grund, nach {veedel} zu schauen.',
    ],
    blackmail: [
      'Uns ist die Adresse Ihres {warehouse} bekannt. {amount}, und sie bleibt es nur uns.',
      'Dr. von Arnim schlägt {amount} vor. Sonst kennt das Präsidium den {warehouse}.',
      'Ihr {warehouse}: schöne Lage. {amount} für unser Schweigen.',
      '{amount}, und der {warehouse} findet in keiner Akte statt.',
      'Für {amount} vergessen wir den {warehouse}. Vollständig.',
    ],
    warnRival: [
      'Ein Hinweis aus dem Konsortium: {enemy} plant gegen Sie.',
      'Man hört im Club, {enemy} sammle Leute.',
      'Der Doktor rät zur Vorsicht. {enemy} ist unterwegs.',
      '{enemy} hat Pläne mit Ihnen. Unschöne.',
      'Unter Geschäftsleuten: Achten Sie auf {enemy}.',
    ],
    favor: [
      'Das Konsortium benötigt diskreten Lagerraum. {amount}.',
      'Dr. von Arnim bittet um eine kleine Gefälligkeit: drei Tage Lagerung, {amount}.',
      'Einige Kisten brauchen einen ruhigen Ort. {amount}.',
      'Eine bezahlte Gefälligkeit: {amount} für Ihren Keller.',
      'Wir zahlen {amount} für Verschwiegenheit und einen Raum.',
    ],
    warAsk: [
      'Das Konsortium klärt eine Angelegenheit mit {enemy} in {veedel}. Möchten Sie beitragen?',
      'Mit {enemy} ist eine Bereinigung fällig. Ihre Hilfe wird honoriert.',
      'Wir ordnen {veedel} neu. {enemy} hat darin keinen Platz. Helfen Sie mit?',
      'Eine Einladung des Doktors: gemeinsam gegen {enemy}.',
      'Wer jetzt gegen {enemy} hilft, hat Freunde im Präsidium.',
    ],
  },
  // 🏭 Nordblock, Serkan Aydın „Beton“: Hochhaus-Ton, Bruder, Beton.
  'mu-nord': {
    warning: [
      'Bruder, {veedel} ist Nordblock. Seit zwanzig Jahren. Verschwinde.',
      'Beton hier. Wir haben dich in {veedel} gesehen. Einmal sag ich das.',
      'In {veedel} verkauft der Block. Du gehörst nicht zum Block.',
      'Hör zu. {veedel} ist hart wie Beton. Du nicht.',
      'Noch ein Tag in {veedel}, und meine Jungs kommen runter aus dem zwölften Stock.',
    ],
    threat: [
      '{tribute} die Woche, Bruder. Sonst kommen wir nach {veedel}.',
      'Beton will {tribute} pro Woche. Dann darfst du in {veedel} bleiben.',
      'Miete für {veedel}: {tribute} wöchentlich. Wie im Block.',
      'Letzte Warnung, Bruder: {tribute} die Woche.',
      '{tribute} pro Woche, oder wir gießen dich ein.',
    ],
    war: [
      'Okay. Dann eben Krieg. Der Block steht zusammen.',
      'Ab heute bist du im Norden Freiwild.',
      'Du hast es so gewollt, Bruder. Jetzt kommt der Beton.',
      'Wir reden nicht mehr. Wir kommen.',
      'Der ganze Block weiß jetzt, wer du bist.',
    ],
    raidWon: [
      'Heute hattest du Glück, Bruder. Das reicht nicht lange.',
      'Respekt. Aber der Block ist groß.',
      'Eins zu null für dich. Wir spielen weiter.',
      'Meine Jungs sind sauer. Das ist schlecht für dich.',
      'Gemerkt. Beton vergisst nicht.',
    ],
    raidLost: [
      'So läuft das im Norden, Bruder.',
      'Deine Ware ist jetzt Nordblock.',
      'Abgeräumt. Grüß deine Leute.',
      'Das war die Miete. Mit Zinsen.',
      'Der Block nimmt, was er will.',
    ],
    attacked: [
      'Du hast einen vom Block angefasst. Jetzt kommt der ganze Block.',
      'Beton ist sauer. Richtig sauer.',
      'Das war mein Cousin, Bruder. Das war ein Fehler.',
      'Im Norden schlägt keiner ungestraft zu.',
      'Du hast den Beton angekratzt. Jetzt bricht was, aber nicht bei uns.',
    ],
    snitch: [
      'Du hast die Bullen in den Block geschickt? Ganz schlechte Idee.',
      'Ein Verräter. Im Block gibt es nichts Schlimmeres.',
      'Wir wissen, wer geredet hat, Bruder.',
      'Die Bullen waren im Treppenhaus. Wegen dir. Das vergessen wir nicht.',
      'Verpfiffen. Von dir. Beton nimmt das persönlich.',
    ],
    tributeDue: [
      'Mietzahlung, Bruder: {tribute}.',
      'Beton kassiert. {tribute}.',
      '{tribute} sind fällig. Bar, am Kiosk.',
      'Neue Woche, {tribute}. Wie immer.',
      'Zahltag im Block: {tribute}.',
    ],
    protectionRefused: [
      'Der Block zahlt nicht. Der Block kassiert.',
      'Kein Geld diese Woche, Bruder.',
      'Abgelehnt. Wir sind der Schutz.',
      'Nichts gibt es. Komm hoch und hol es dir.',
      'Beton sagt Nein.',
    ],
    offer: [
      'Bruder, {amount} übrig. {price}, abholen in {veedel}.',
      'Beton. {amount} für {price}. Tiefgarage in {veedel}.',
      'Aus dem Keller: {amount}, {price}. In {veedel}.',
      'Sonderpreis vom Block: {amount} für {price}, {veedel}.',
      '{amount} müssen weg. {price}. Komm nach {veedel}.',
    ],
    allianceOffer: [
      '{enemy} macht Stress. {price}, und du bist im Block.',
      'Beton bietet: zusammen gegen {enemy}. {price}.',
      'Wir brauchen Leute gegen {enemy}, Bruder. {price}.',
      'Der Block gegen {enemy}. Dein Einsatz: {price}.',
      'Gemeinsam machen wir {enemy} platt. Kostet {price}.',
    ],
    intimidation: [
      'Meine Jungs stehen jetzt {atSpot}, Bruder. Deine Kunden gehen woanders hin.',
      '{AtSpot} ist jetzt Block. Unser Block.',
      '{AtSpot} sind heute wir. Viel Glück.',
      'Sechs von uns {atSpot}. Keiner kauft bei dir.',
      'Beton steht jetzt {atSpot}.',
    ],
    tipOff: [
      'Die Bullen wissen jetzt, was in {veedel} läuft, Bruder.',
      'Beton hat telefoniert. {veedel} wird heiß.',
      'Ein Anruf, und {veedel} ist voller Streifen.',
      'Wir haben den Bullen was über {veedel} erzählt.',
      'Grüße aus dem Norden: {veedel} wird kontrolliert.',
    ],
    blackmail: [
      'Bruder, ich kenn deinen {warehouse}. {amount}, sonst kennen ihn die Bullen.',
      'Beton. {amount}, oder der {warehouse} ist morgen versiegelt.',
      'Dein {warehouse}, schöne Ecke. {amount}, und ich vergess sie.',
      '{amount} auf die Hand, Bruder, und dein {warehouse} bleibt sauber.',
      'Für {amount} hab ich vom {warehouse} nie was gehört.',
    ],
    warnRival: [
      'Bruder, {enemy} will dir an den Kragen.',
      'Beton hier. {enemy} plant was. Pass auf.',
      'Im Block erzählt man: {enemy} kommt zu dir.',
      '{enemy} sammelt Jungs. Gegen dich.',
      'Kleiner Tipp: {enemy} sucht Stress mit dir.',
    ],
    favor: [
      'Bruder, wir brauchen Platz für ein paar Kisten. {amount}.',
      'Beton. Kannst du was lagern? {amount}.',
      'Der Block ist zu heiß gerade. Nimm unser Zeug, {amount}.',
      'Unter Brüdern: {amount}, wenn unsere Kisten bei dir stehen dürfen.',
      'Wir brauchen deine Garage. {amount}.',
    ],
    warAsk: [
      'Der Block geht auf {enemy} los, in {veedel}. Bist du dabei, Bruder?',
      'Heute Nacht räumen wir {enemy} weg. Wer hilft, ist Familie.',
      '{enemy} hat in {veedel} nichts zu suchen. Hilf uns.',
      'Ich frag einmal, Bruder: gegen {enemy}, ja oder nein?',
      'Der Nordblock gegen {enemy}. Wer jetzt kneift, ist raus.',
    ],
  },
};
